TE-3.1: Base Hierarchical Route Installation - porting script changes from ATE to OTG location
openconfig/featureprofiles pull request #1010
Opened 2023-01-24 19:46 UTC by stthummuri

Ported changes from https://github.com/openconfig/featureprofiles/pull/850 to OTG location script 	https://github.com/openconfig/featureprofiles/blob/main/feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go

2023-01-25 23:04 UTC, stthummuri commented
@michaelore Can you please review and merge this PR

2023-02-02 01:05 UTC, stthummuri commented on feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
> +		if got := nh.GetIpAddress(); got != atePort2.IPv4 {
Done.

2023-02-02 01:05 UTC, stthummuri commented on feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
> +// TODO: the below code checks entries for each level of the hierarchy statically. We need to create a helper function that does the check recursively.
Done.

2023-02-02 01:06 UTC, stthummuri commented on feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
> +			// note that b->c is validated in the next code block
Done.

2023-02-02 01:06 UTC, stthummuri commented on feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
> +		// for devices that return  the nexthop with resolving it recursively. For a->b->c the device returns c
Done.

2023-02-02 11:29 UTC, michaelore requested changes

2023-02-02 11:29 UTC, michaelore commented on feature/gribi/otg_tests/base_hierarchical_route_installation_test/base_hierarchical_route_installation_test.go
> +// TODO: the below code checks entries for each level of the hierarchy statically. We need to create a helper function that does the check recursively.
I was thinking we'd capitalize "the"->"The"

"TODO: The below code..."

2023-02-02 21:01 UTC, stthummuri commented
Done --- 
I was thinking we'd capitalize "the"->"The"

"TODO: The below code..."

2023-02-03 10:54 UTC, michaelore commented
/gcbrun

2023-02-03 12:08 UTC, michaelore approved these changes

2023-02-03 12:08 UTC, merged