DP-1.4: Handle differences in QoS queue names/numbers across vendors
openconfig/featureprofiles pull request #1087
Opened 2023-02-09 00:13 UTC by sgirishj

Handle differences in QoS queue names/numbers across vendors.

2023-02-09 22:23 UTC, xw-g commented
@Hobbydos can you help comment for Nokia? Thanks.

2023-02-10 17:54 UTC, sezhang2 requested changes
Please wait for https://github.com/openconfig/featureprofiles/pull/1100 to be merged.

2023-02-10 23:25 UTC, sachendras approved these changes

2023-02-10 23:49 UTC, sezhang2 commented
What is the reason to change the queue names?

2023-02-11 00:10 UTC, sgirishj commented
> 

Queues are identified using numeric values 0-7 in Juniper's case. Added switch-case construct where such nomenclature is needed. For the other vendors, names are left to what they were in the script previously.

2023-02-11 00:10 UTC, sgirishj commented
Closed by mistake. Reopening.

2023-02-11 00:17 UTC, sezhang2 commented
> 

Do you have a bug to track this limitation?

2023-02-11 01:37 UTC, sgirishj commented
> > 
> 
> Do you have a bug to track this limitation?

No. Is there a requirement?

2023-02-11 01:46 UTC, sezhang2 commented
> > > 
> > 
> > 
> > Do you have a bug to track this limitation?
> 
> No. Is there a requirement?

It is a workaround to use queue number. The requirement is to use queue name, so we need to track this workaround.

From https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-qos.html#qos-interfaces-interface-output-queues-queue-name

**/qos/queues/queue/config/
name
description:
User-defined name of the queue

nodetype: leaf (rw)
type: string**

2023-02-13 17:55 UTC, greg-dennis requested changes

2023-02-13 17:55 UTC, greg-dennis commented on feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
> +	var q_BE1, q_BE0, q_AF1, q_AF2, q_AF3, q_AF4, q_NC1 string
underscores are not allowed in go variable name style. I'd probably create an inline type here:

	type qosVals struct {
		be0, be1, af1, af2, af3, af4, nc1 string
	}
	qos := qosVals {
		be0: "BE0",
		be1: "BE1",
		af1: "AF1",
		af2: "AF2",
		af3: "AF3",
		af4: "AF4",
		nc1: "NC1",
	}
	if dut.Vendor() == ondatra.JUNIPER {
		qos = qosVals {
			be0: "7",
			be1: "0",
			af1: "4",
			af2: "1",
			af3: "5",
			af4: "2",
			nc1: "3",
		}
	}

2023-02-13 17:55 UTC, greg-dennis commented on feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
>  		targetGrpoup: "target-group-BE1",
please fix the misspelling "targetGroup"

2023-02-13 20:52 UTC, sezhang2 submitted a review, later dismissed
Per the discussion, it is a workaround. It should be fixed via b/269154477.

2023-02-14 03:23 UTC, greg-dennis approved these changes

2023-02-14 03:29 UTC, greg-dennis commented
/gcbrun

2023-02-14 05:46 UTC, merged