OTG Test - TE-11.3: Backup NHG: Actions
openconfig/featureprofiles pull request #1125
Opened 2023-02-15 00:05 UTC by octpetre

OTG conversion of _TE-11.3: Backup NHG: Actions_
Fixes #1005

2023-03-13 19:12 UTC, jasdeep-hundal requested changes

2023-03-13 19:12 UTC, jasdeep-hundal commented on feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
> +	outerIPHeader.Dst().Increment().SetStart(dstPfx).SetCount(1)
This is just equivalent to the `SetValue(dstPfx)` right? (I see that it's similar in the ATE test as well, not sure of the intent there.)

2023-03-14 18:02 UTC, octpetre commented on feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
> +func createFlow(t *testing.T, ate *ondatra.ATEDevice, top gosnappi.Config, name string, dstPfx string, dst *attrs.Attributes) gosnappi.Flow {
Removed

2023-03-14 18:53 UTC, jasdeep-hundal commented on feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
> +	outerIPHeader.Dst().Increment().SetStart(dstPfx).SetCount(1)
Will resolve outside of this PR.

2023-03-14 18:53 UTC, jasdeep-hundal commented
/gcbrun

2023-03-14 18:57 UTC, jasdeep-hundal commented on feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
> +func createFlow(t *testing.T, ate *ondatra.ATEDevice, top gosnappi.Config, name string, dstPfx string, dst *attrs.Attributes) gosnappi.Flow {
@octpetre : Not seeing the changes in the latest code, may need another push here.

2023-03-14 19:39 UTC, octpetre commented on feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
> +func createFlow(t *testing.T, ate *ondatra.ATEDevice, top gosnappi.Config, name string, dstPfx string, dst *attrs.Attributes) gosnappi.Flow {
Done

2023-03-15 19:06 UTC, jasdeep-hundal commented
/gcbrun

2023-03-15 19:07 UTC, jasdeep-hundal requested changes

2023-03-15 19:07 UTC, jasdeep-hundal commented on feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
> +func createFlow(t *testing.T, ate *ondatra.ATEDevice, name string, dstPfx string, dst *attrs.Attributes) gosnappi.Flow {
Can still remove `t`

2023-03-21 15:40 UTC, octpetre commented on feature/experimental/gribi/otg_tests/backup_nhg_action/backup_nhg_action_test.go
> +func createFlow(t *testing.T, ate *ondatra.ATEDevice, name string, dstPfx string, dst *attrs.Attributes) gosnappi.Flow {
Removed

2023-03-22 20:09 UTC, jasdeep-hundal commented
/gcbrun

2023-03-22 22:32 UTC, jasdeep-hundal approved these changes

2023-03-24 00:03 UTC, merged