Update qos_output_queue_counters_test.go
openconfig/featureprofiles pull request #1131
Opened 2023-02-15 20:11 UTC by saarvind6481

2023-02-16 07:34 UTC, sezhang2 requested changes
Can you explain why rename queue names?

Please also mention that why vendor specific workarounds are needed? Is there any bug to track the workaround?

2023-02-16 16:07 UTC, aaronmillisor commented
> Can you explain why rename queue names?
> 
> Please also mention that why vendor specific workarounds are needed? Is there any bug to track the workaround?

At least part of the problem really stems from a deficiency in the OC-QoS model. Silicon One ASIC's, similar to many others in the industry, have a concept called a 'traffic-class' which also exists in many other asics. This traffic-class is a numeric identifier.

In IOS XR's configuration model, this traffic class has a [tight coupling to a specific priority value in the case of strict priority schedulers](https://www.cisco.com/c/en/us/td/docs/iosxr/cisco8000/qos/70x/configuration/guide/b-qos-cg-8k-70x/traffic_management_overview.html#concept_izx_bhw_m3b).

The missing traffic-class equivalent has been a long-standing concern for this model, however it now appears to be getting addressed through the introduction of queue-identifiers in [pull 772 for OC-QoS](https://github.com/openconfig/public/pull/772).

The way that this missing functionality is addressed seems to be varying across implementors. In XR we are allocating the traffic-class in the order they appear in config to satisfy the ordering requirements of the scheduling model. In order to get this to show up properly via OC, we are using queue names that are defined lexically ordered according to the desired scheduling policy.

Alternatives that implementors may use could include fixed queue names with an out of band association, or magic fixed queue names. Each approach has downsides.

We expect this ordering issue to be addressed after the merge of PR772.

Separately, QoS scheduling models are likely to vary across hardware platforms, and should be expected to change according to the asic/os implementation even when OC is used.

2023-02-16 16:16 UTC, dplore commented
Operationally I'd like to keep the queue names the same. But we can use CLI
commands to map the traffic class identifiers to the open config queue
names.

The OC model solution for this specific scenario will be merged soon.



On Thu, Feb 16, 2023, 8:07 AM Aaron Millisor ***@***.***>
wrote:

> Can you explain why rename queue names?
>
> Please also mention that why vendor specific workarounds are needed? Is
> there any bug to track the workaround?
>
> At least part of the problem really stems from a deficiency in the OC-QoS
> model. Silicon One ASIC's, similar to many others in the industry, have a
> concept called a 'traffic-class' which also exists in many other asics.
> This traffic-class is a numeric identifier.
>
> In IOS XR's configuration model, this traffic class has a tight coupling
> to a specific priority value in the case of strict priority schedulers
> <https://www.cisco.com/c/en/us/td/docs/iosxr/cisco8000/qos/70x/configuration/guide/b-qos-cg-8k-70x/traffic_management_overview.html#concept_izx_bhw_m3b>
> .
>
> The missing traffic-class equivalent has been a long-standing concern for
> this model, however it now appears to be getting addressed through the
> introduction of queue-identifiers in pull 772 for OC-QoS
> <https://github.com/openconfig/public/pull/772>.
>
> The way that this missing functionality is addressed seems to be varying
> across implementors. In XR we are allocating the traffic-class in the order
> they appear in config to satisfy the ordering requirements of the
> scheduling model. In order to get this to show up properly via OC, we are
> using queue names that are defined lexically ordered according to the
> desired scheduling policy.
>
> Alternatives that implementors may use could include fixed queue names
> with an out of band association, or magic fixed queue names. Each approach
> has downsides.
>
> We expect this ordering issue to be addressed after the merge of PR772.
>
> Separately, QoS scheduling models are likely to vary across hardware
> platforms, and should be expected to change according to the asic/os
> implementation even when OC is used.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openconfig/featureprofiles/pull/1131#issuecomment-1433330155>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABMCGM7TUFSPGC22BGDORDDWXZGEHANCNFSM6AAAAAAU5JJMMU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-02-21 21:15 UTC, guoshiuan commented
Internal test result: b/269634520

2023-02-22 18:12 UTC, prinikasn reviewed
/gcbrun

2023-02-22 18:57 UTC, prinikasn approved these changes

2023-02-22 22:41 UTC, sezhang2 commented on feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
> +			"flow-af2": {frameSize: 1200, trafficRate: 2, dscp: 19, queue: "d_AF2"},
why change DSCP from 16 to 19?

2023-02-22 22:57 UTC, sezhang2 submitted a review, later dismissed
Per the discussion with [aaronmillisor](https://github.com/aaronmillisor) yesterday, please add the bug# for the workaround.

Please also address the comment about DSCP change as well.

2023-02-28 04:28 UTC, thesrinath commented
/gcbrun

2023-02-28 05:45 UTC, sezhang2 reviewed
Does the test pass in your test bed with this PR?

2023-02-28 05:48 UTC, guoshiuan commented
> Does the test pass in your test bed with this PR?

Internal test result: b/269634520

2023-03-02 17:07 UTC, saarvind6481 commented on feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
> +			"flow-af2": {frameSize: 1200, trafficRate: 2, dscp: 19, queue: "d_AF2"},
I have resubmitted the PR with DSCP 16

2023-03-02 20:07 UTC, guoshiuan commented
We (Sean, Viktor, Cisco team and I) had a discussion (b/268403096#comment9). Viktor has filed bugs to track the explanation of Cisco implementation, and we decided to move forward with this PR.

2023-03-02 20:07 UTC, guoshiuan approved these changes

2023-03-02 20:15 UTC, prinikasn approved these changes

2023-03-02 21:25 UTC, merged