Update one_sp_queue_traffic_test.go
openconfig/featureprofiles pull request #1157
Opened 2023-02-20 16:24 UTC by saarvind6481

Pull request from cisco for dp-1.7

2023-02-21 03:26 UTC, sezhang2 requested changes
I am still working on this experimental code. Please wait.

2023-02-21 21:46 UTC, sezhang2 commented on feature/experimental/qos/ate_tests/one_sp_queue_traffic_test/one_sp_queue_traffic_test.go
> +			dscp:                  19,
What is the reason to change the DSCP value from 16 to 19?

2023-02-28 04:29 UTC, thesrinath commented
/gcbrun

2023-03-02 22:35 UTC, sezhang2 approved these changes
Per the discussion, approve the PR as  a workaround.

2023-03-02 23:32 UTC, guoshiuan commented
b/271033767 has the internal test results.

2023-03-02 23:36 UTC, prinikasn reviewed
/gcbrun

2023-03-02 23:36 UTC, guoshiuan commented
/gcbrun

2023-03-02 23:53 UTC, prinikasn approved these changes

2023-03-02 23:53 UTC, merged