Replace hardcoded Hadware Port name check with presence check
openconfig/featureprofiles pull request #1212
Opened 2023-03-03 23:52 UTC by sgirishj

Script was expecting specific hardcoded string formation for the below leaf which appears to be vendor specific:
/interfaces/interface/state/hardware-port

<snip>
// Derive hardware port from interface name by removing the port number.
// For example, Ethernet3/35/1 hardware port is Ethernet3/35.
</snip>

Replaced it with a check for the presence of the leaf.

2023-03-06 20:09 UTC, greg-dennis submitted a review, later dismissed
Approving for Go quality only

2023-03-13 16:53 UTC, sachendras commented on feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +	got := gnmi.Lookup(t, dut, gnmi.OC().Interface(dp.Name()).HardwarePort().State())
Can we have a Juniper case to address Juniper specific interface naming.

2023-03-15 19:28 UTC, sachendras commented
/gcbrun

2023-03-23 02:53 UTC, sachendras commented
Please modify the test as per https://github.com/openconfig/featureprofiles/pull/1318

2023-03-23 22:23 UTC, greg-dennis requested changes

2023-03-23 22:23 UTC, greg-dennis commented on feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +
delete blank line

2023-03-23 22:23 UTC, greg-dennis commented on feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +	// Verify HardwarePort leaf is present under interface
period at end of sentence comment

2023-03-23 22:23 UTC, greg-dennis commented on feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +	// Verify HardwarePort is a component of type PORT
period at end of sentence comment

2023-03-23 22:23 UTC, greg-dennis commented on feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +	// Verify HardwarePort component has CHASSIS as an ancestor
period at end of sentence comment

2023-03-23 22:23 UTC, greg-dennis commented on feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +// a component of type CHASSIS as an ancestor
period at end of sentence comment

2023-03-24 02:14 UTC, greg-dennis approved these changes
Approving for Go quality only

2023-03-24 02:14 UTC, greg-dennis commented
/gcbrun

2023-03-24 21:34 UTC, mojiiba approved these changes

2023-03-27 17:34 UTC, merged