Make addrundata write metadata.textproto files
openconfig/featureprofiles pull request #1293
Opened 2023-03-17 03:25 UTC by greg-dennis

2023-03-17 20:44 UTC, liulk requested changes

2023-03-17 20:44 UTC, liulk commented on tools/addrundata/README.md
> +# proto-file: proto/metadata.proto
Should we fully-qualify the proto file with repo?

github.com/openconfig/featureprofiles/proto/metadata.proto

2023-03-17 20:44 UTC, liulk commented on tools/addrundata/case.go
> +		return fmt.Errorf("could not parse metadata.textproto: %w", err)
Break a long line?

```suggestion
	err := readFile(filepath.Join(testdir, "metadata.textproto"), tc.existing.fromProto)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("could not parse metadata.textproto: %w", err)
```

2023-03-17 20:44 UTC, liulk commented on tools/addrundata/case.go
> +	existing   parsedData // From existing source code.
```suggestion
	existing   parsedData // From existing metadata or deprecated rundata_test.go.
```

2023-03-17 20:44 UTC, liulk commented on tools/addrundata/main.go
> +	checkDeprecated = flag.Bool("check_deprecated", false, "whether to check for the existence of deprecated rundata_test.go files")
checkDeprecated -> deprecateRundataTestGo?

2023-03-17 20:44 UTC, liulk commented on tools/addrundata/rundata.go
> +	var foundInit bool
Don't need this?

2023-03-17 20:44 UTC, liulk commented on tools/addrundata/rundata.go
> +	}
This initializes pd, so we don't need to care about setting fields conditionally.

```suggestion
	pd.testUUID = md.GetUuid()
	pd.testPlanID = md.GetPlanId()
	pd.testDescription = md.GetDescription()
```

2023-03-17 20:44 UTC, liulk commented on tools/addrundata/rundata.go
> +// write generates a complete metadata.textproto to the writer.
Request change: we cannot simply overwrite metadata with only these fields. If there are other fields present in the metadata (e.g. testbed, config and telemetry coverage), we have to preserve them.

2023-03-21 19:21 UTC, greg-dennis commented
Deleting this PR as the new plan splits the work into three different PRs

2023-03-21 19:21 UTC, closed without merging

2023-03-21 21:44 UTC, liulk commented
Continued as #1303