TE-13.1: Add Arista support for CoreFileCheck functionality and fix an issue with configuring parent L3 interface
openconfig/featureprofiles pull request #1387
Opened 2023-04-04 21:15 UTC by sambhavjain-204

- Adding support for vendor Arista for the `coreFileCheck` functionality in this test.
- Fixing the issue with configuring L3 parent interface on the lines of other similar test TE-13.2

2023-04-05 04:42 UTC, rszarecki submitted a review, later dismissed

2023-04-11 23:35 UTC, mohanasm requested changes

2023-04-13 00:27 UTC, rszarecki requested changes
Please have a look at line 300.
I belive it should be : "for i := 0; i <= nextHopCount; i++ {"
since change in line 284 "vlanID := uint16(i)" makes vlan starting form 0.

2023-04-17 14:42 UTC, sambhavjain-204 commented on feature/experimental/gribi/ate_tests/route_addition_during_failover_test/route_addition_during_failover_test.go
> +		vlanID := uint16(i)
I have reverted the changes for `vlanID` and `Index`

2023-05-01 16:55 UTC, rszarecki commented
/cbrun

2023-05-01 16:56 UTC, rszarecki commented
/gcbrun

2023-05-01 16:56 UTC, rszarecki approved these changes

2023-05-01 21:18 UTC, merged