OTG: textproto and lag testbed file changes
openconfig/featureprofiles pull request #1441
Opened 2023-04-19 19:44 UTC by stthummuri

1. Added third interface in juniper_cptx.textproto because some ondatra featureprofiles scripts need three ports dut
2. Added new testbed file atedut_lag_4.testbed which is needed to run scripts on <vendor>_lag.textproto topologies

2023-04-20 14:48 UTC, octpetre commented
@stthummuri I have addressed the missing testbed file into #1442. You can remove it from here so we don't have duplicates.

2023-04-24 21:36 UTC, octpetre requested changes

2023-04-24 21:36 UTC, octpetre commented on topologies/atedut_lag_4.testbed
Please remove this file. The original topologies/kne/atedut_lag.testbed file will be restored in #1442 and we don't need a new one

2023-04-27 04:05 UTC, sachendras commented on topologies/atedut_lag_4.testbed
[stthummuri](https://github.com/stthummuri) can you please close the comments here?

2023-04-27 15:37 UTC, stthummuri commented on topologies/atedut_lag_4.testbed
Will close this PR since the atedut_lag.testbed file will be restored in https://github.com/openconfig/featureprofiles/pull/1442 . Same file will be used for topo with more than 2 ports.

2023-04-27 15:37 UTC, stthummuri commented
Closing this PR since the atedut_lag.testbed file will be restored in https://github.com/openconfig/featureprofiles/pull/1442 . Same file will be used for topo with more than 2 ports.

2023-04-27 15:37 UTC, closed without merging