OTG RT-1.3: BGP Route Propagation (Add WatchAll)
openconfig/featureprofiles pull request #1489
Opened 2023-05-02 10:52 UTC by ANISH-GOTTAPU

resolves #1488 

BGP Route Propagation test has GetAll which retrieves learnt prefixes. GetAll fails sometimes when BGP is taking sometime to exchange the routes.

Added WatchAll with timer to check if routes are learnt.

2023-05-06 00:44 UTC, jasdeep-hundal requested changes

2023-05-06 00:44 UTC, jasdeep-hundal commented on feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
>  func checkOTGBGP4Prefix(t *testing.T, otg *otg.OTG, config gosnappi.Config, expectedOTGBGPPrefix OTGBGPPrefix) bool {
Add t.Helper.

2023-05-06 00:44 UTC, jasdeep-hundal commented on feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
> +		t.Errorf("The BGP prefixes are not being learned.")
Don't need t.Errorf here, error is reported in the main test function. Can also drop the else block and just have `return false`.

2023-05-06 00:44 UTC, jasdeep-hundal commented on feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
>  func checkOTGBGP6Prefix(t *testing.T, otg *otg.OTG, config gosnappi.Config, expectedOTGBGPPrefix OTGBGPPrefix) bool {
Add t.helper

2023-05-06 00:44 UTC, jasdeep-hundal commented on feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
> +		t.Errorf("The BGP prefixes are not being learned.")
Don't need t.Errorf here, error is reported in the main test function. Can also drop the else block and just have `return false`.

2023-05-06 00:44 UTC, jasdeep-hundal commented on feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
>  // }
Can remove above TODO/commented-out function.

2023-05-10 18:43 UTC, jasdeep-hundal commented
/gcbrun

2023-05-11 20:16 UTC, thesrinath approved these changes

2023-05-11 20:17 UTC, jasdeep-hundal approved these changes

2023-05-11 20:17 UTC, jasdeep-hundal commented
/gcbrun

2023-05-11 22:03 UTC, merged