Fix P4RT-2.1: P4RT Election test failure for EOS
openconfig/featureprofiles pull request #1501
Opened 2023-05-03 00:01 UTC by prakashbadri-arista

In EOS, P4RT-2.1: P4RT Election test was failing for the following reasons
1 - EOS allows 0 election id as valid for being elected as a primary
    client . A deviation (P4rtUnsetElectionIDPrimaryAllowed) has been added to the test to expect different status code
  in TestUnsetElectionid. Also the test has been updated to allow
  SetForwardingPipelineConfig from a primary with election id of 0

  2 - EOS always sends ALREADY_EXISTS in status code to secondary
    clients in the response to primaryAribitrationMessage when the election id
    is lesser than the current/previous primary election id. According
    to P4RT specification, ALREADY_EXISTS status is set when primary is
    present and NOT_FOUND is set when there is no primary. I am adding a
    deviation to expect ALREADY_EXISTS instead of NOT_FOUND status until
    EOS behavior is updated.

    The test needs to be run with the following deviations with EOS:
    -deviation_interface_enabled
    -deviation_p4rt_missing_delete
    --deviation_p4rt_unsetelectionid_primary_allowed
    -deviation_bkup_arbitration_resp_code

2023-05-09 23:05 UTC, prinikasn requested changes

2023-05-09 23:05 UTC, prinikasn commented on internal/deviations/deviations.go
> +	P4rtUnsetElectionIDPrimaryAllowed = flag.Bool("deviation_p4rt_unsetelectionid_primary_allowed", false, "Device allows unset Election ID to be primary")
Please use the new style guide to  add deviations i.e by using accessor methods and making this parameter private (lowercase)

2023-05-09 23:06 UTC, prinikasn commented on internal/deviations/deviations.go
> +	P4rtUnsetElectionIDPrimaryAllowed = flag.Bool("deviation_p4rt_unsetelectionid_primary_allowed", false, "Device allows unset Election ID to be primary")
Refer to https://github.com/openconfig/featureprofiles/pull/1397/files for example

2023-05-09 23:11 UTC, Ankur19 commented on feature/experimental/p4rt/tests/p4rt_election/p4rt_election_test.go
> +			test.wantStatus = 6
nit: can you change the hardcoded numbers to something like: `int32(codes.ALREADY_EXISTS)` and `int32(codes.NOT_FOUND)`

2023-05-10 22:40 UTC, rszarecki approved these changes

2023-05-10 22:54 UTC, rszarecki commented
/gcbrun

2023-05-10 23:15 UTC, rszarecki approved these changes

2023-05-10 23:15 UTC, rszarecki approved these changes

2023-05-19 17:42 UTC, rszarecki commented
/gcbrun

2023-05-26 15:58 UTC, rszarecki commented
/gcbrun

2023-05-26 16:10 UTC, rszarecki approved these changes

2023-05-26 16:10 UTC, rszarecki approved these changes

2023-05-26 17:24 UTC, prinikasn approved these changes
LGTM for deviation style guide

2023-05-26 18:16 UTC, merged