Add devations to metadata proto
openconfig/featureprofiles pull request #1643
Opened 2023-05-18 06:17 UTC by prinikasn

Add devations to metadata proto
Also updating Makefile and proto lint workflow to include the ondatra testbed.proto dependency

2023-05-18 06:21 UTC, prinikasn commented
As discussed offline, I am stating with just adding one deviation to the proto at a time.

2023-05-19 17:34 UTC, greg-dennis requested changes
two bash nits

2023-05-19 17:34 UTC, greg-dennis commented on .github/workflows/pull_request.yml
> +        find . -name \*.proto -exec api-linter -I./${PROTOBUF_IMPORT_DIR} --disable-rule all --enable-rule core {} \+
put quotes around "${PROTOBUF_IMPORT_DIR}"

2023-05-19 17:34 UTC, greg-dennis commented on .github/workflows/pull_request.yml
> +        PROTOBUF_IMPORT_DIR='protobuf-import'
put "readonly " before PROTOBUF_IMPORT_DIR='protobuf-import'

2023-05-19 17:58 UTC, prinikasn commented on .github/workflows/pull_request.yml
> +        find . -name \*.proto -exec api-linter -I./${PROTOBUF_IMPORT_DIR} --disable-rule all --enable-rule core {} \+
done

2023-05-19 17:58 UTC, prinikasn commented
> two bash nits

done. Also updated PlatformExceptions to be a repeated field

2023-05-19 19:52 UTC, greg-dennis approved these changes

2023-05-19 21:03 UTC, merged