OTG Tests Update - RT-5.2 and RT-5.4
openconfig/featureprofiles pull request #1661
Opened 2023-05-26 16:54 UTC by octpetre

Adding systemId to otg LACP settings for RT-5.2 and RT-5.4
Resolves #558
Resolves #1273

2023-06-01 21:45 UTC, jasdeep-hundal requested changes
@octpetre : Please rebase to capture changes from https://github.com/openconfig/featureprofiles/pull/1660 (which also made the same deviation updates to the aggregate test.)

2023-06-05 22:34 UTC, guoshiuan commented on feature/interface/aggregate/otg_tests/aggregate_forwarding_viable_test/aggregate_forwarding_viable_test.go
> +		agg.Protocol().Lacp().SetActorKey(1).SetActorSystemPriority(1).SetActorSystemId(ateDst.MAC)
can you run gofmt?

2023-06-06 00:49 UTC, jasdeep-hundal commented
/gcbrun

2023-06-06 00:49 UTC, jasdeep-hundal approved these changes

2023-06-06 01:56 UTC, merged