Update qos_output_queue_counters_test.go
openconfig/featureprofiles pull request #1671
Opened 2023-05-28 10:54 UTC by saarvind6481

Update cisco-dp-1.4-uprev

2023-06-02 21:59 UTC, prinikasn requested changes
Please make the applicable changes to tests under otg_tests/folder too

2023-06-09 23:31 UTC, guoshiuan commented on feature/qos/otg_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
> -		if !deviations.QOSDroppedOctets(dut) {
Don't remove this deviation flag check; it is still used by other vendor.

2023-06-10 00:43 UTC, guoshiuan commented on feature/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
> -package qos_output_queue_counters_test
Why do you change the package name?

2023-06-12 22:12 UTC, guoshiuan approved these changes

2023-06-12 22:30 UTC, prinikasn approved these changes

2023-06-12 22:33 UTC, merged