Update Readme per PR#1538 changes
openconfig/featureprofiles pull request #1681
Opened 2023-05-30 16:37 UTC by arvbaska1

Updated Readme files for RT-1.5, RT-1.7, RT-1.10 for RPL under BGP peer-group AFI/SAFI instead of neighbor AFI/SAFI

2024-10-10 01:30 UTC, dplore requested changes
LGTM, but please resolve conflict on feature/bgp/prefixlimit/ate_tests/bgp_prefix_limit_test/README.md

2024-12-27 05:28 UTC, self-maurya approved these changes

2024-12-27 05:36 UTC, self-maurya submitted a review, later dismissed

2024-12-27 05:57 UTC, self-maurya approved these changes

2024-12-27 06:02 UTC, self-maurya submitted a review, later dismissed

2024-12-27 06:09 UTC, self-maurya approved these changes

2024-12-27 06:39 UTC, merged