Migrate ipv4_missing_enabled deviation to metadata proto files
openconfig/featureprofiles pull request #1719
Opened 2023-06-06 01:35 UTC by jasdeep-hundal

2023-06-06 20:58 UTC, jasdeep-hundal commented
Validated on ATE/OTG versions of:
- DUT Daemon Failure
- Telemetry Basic Check Test
- Singleton Test
- Default Address Families

2023-06-06 23:42 UTC, prinikasn approved these changes

2023-06-06 23:47 UTC, prinikasn requested changes
I think these deviation might also have to be added to base_adjencencies and lsp_update_test

2023-06-07 17:24 UTC, jasdeep-hundal commented
Updated remaining tests that I missed in the first version of the patch. Tested additionally on both ATE/OTG versions of
- Backup NHG
- Route Installation
- Route Removal on non-default VRF

2023-06-07 19:12 UTC, greg-dennis approved these changes

2023-06-07 20:22 UTC, greg-dennis approved these changes

2023-06-07 20:32 UTC, prinikasn approved these changes

2023-06-07 20:40 UTC, merged