Move to a flag deviation
openconfig/featureprofiles pull request #1768
Opened 2023-06-16 15:54 UTC by Ankur19

2023-06-16 17:45 UTC, greg-dennis commented
Why is this being moved back to a flag?

2023-06-16 19:11 UTC, prinikasn requested changes
Why are we moving this back to a flag?

2023-06-26 23:29 UTC, rszarecki approved these changes

2023-06-27 14:40 UTC, prinikasn approved these changes

2023-06-27 14:46 UTC, merged