Add gribi feature textproto
openconfig/featureprofiles pull request #1772
Opened 2023-06-19 20:50 UTC by xw-g

2023-07-11 15:10 UTC, bensons commented
@xw-g

It appears that this PR is failing the Validate OpenConfig Paths check. The error seems to be:
  file: /home/runner/work/featureprofiles/featureprofiles/feature/gribi/feature.textproto
    line 36: missing from YANG "/network-instances/network-instance/afts/next-hop-groups/next-hop-group/next-hops/next-hop/state/id"
    line 63: missing from YANG "/network-instances/network-instance/afts/next-hops/next-hop/state/ip-in-ip/state/src-ip"
    line 66: missing from YANG "/network-instances/network-instance/afts/next-hops/next-hop/state/ip-in-ip/state/dst-ip"

2023-07-12 00:21 UTC, dplore requested changes

2023-07-12 00:21 UTC, dplore commented on feature/gribi/feature.textproto
> +  path: "/network-instances/network-instance/afts/next-hops/next-hop/state/ip-in-ip/state/src-ip"
```suggestion
  path: "/network-instances/network-instance/afts/next-hops/next-hop/ip-in-ip/state/src-ip"
```

2023-07-12 00:21 UTC, dplore commented on feature/gribi/feature.textproto
> +  path: "/network-instances/network-instance/afts/next-hops/next-hop/state/ip-in-ip/state/dst-ip"
```suggestion
  path: "/network-instances/network-instance/afts/next-hops/next-hop/ip-in-ip/state/dst-ip"
```

2023-07-12 00:21 UTC, dplore commented on feature/gribi/feature.textproto
> +  path: "/network-instances/network-instance/afts/next-hop-groups/next-hop-group/next-hops/next-hop/state/id"
```suggestion
  path: "network-instances/network-instance/afts/next-hop-groups/next-hop-group/next-hops/next-hop/state/index"
```

2023-07-12 00:57 UTC, dplore approved these changes

2023-07-12 16:15 UTC, merged