gnsi binding
openconfig/featureprofiles pull request #1879
Opened 2023-07-13 17:39 UTC by mojiiba

This pull adds gnsi to static binding. This requires https://github.com/openconfig/ondatra/pull/82 to be merged first.

2023-07-18 21:30 UTC, guoshiuan approved these changes

2023-07-19 18:55 UTC, greg-dennis commented
@mojiiba, can you update this PR to use the latest Ondatra release with gnsi support and ping back when done? Thanks!

2023-07-19 20:09 UTC, greg-dennis requested changes

2023-07-19 20:09 UTC, greg-dennis commented on topologies/binding/gnsi.go
> +// Copyright 2022 Google LLC
2023

2023-07-19 20:09 UTC, greg-dennis commented on topologies/binding/gnsi.go
> +var _ = binding.GNOIClients(gnoiConn{})
gnoi->gnsi

2023-07-19 22:49 UTC, mojiiba commented on topologies/binding/gnsi.go
> +var _ = binding.GNOIClients(gnoiConn{})
done

2023-07-19 22:49 UTC, mojiiba commented on topologies/binding/gnsi.go
> +// Copyright 2022 Google LLC
done

2023-07-20 02:00 UTC, greg-dennis approved these changes

2023-07-20 02:00 UTC, merged