OTG TE-2.1 Update - ATE test sync and more
openconfig/featureprofiles pull request #1933
Opened 2023-07-24 14:44 UTC by octpetre

- ATE test sync
- converted lossPct to float
- replaced port stats verification to flow stats verification now
Resolves #566

2023-08-18 01:46 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
Needs to be updated past the merge of PR 1988, but changes otherwise look good.

Couple requested simplifications:
- Can we use underscores in the flow name directly instead of `modName`? (https://github.com/openconfig/featureprofiles/pull/1933/files#diff-446a8de58a33efff05bd4b6a8f500e980eb8aac9e163e869a2b62fc483054cc8L480)
- This comment is no longer valid:

2023-08-18 01:50 UTC, jasdeep-hundal requested changes

2023-08-18 01:50 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
Needs to be updated past the https://github.com/openconfig/featureprofiles/commit/0ef32a2080a63b9b899ae395ca0aaf85e7086969, but changes otherwise look good.

Couple requested simplifications:
- Can we use underscores in the flow name directly instead of modName? (https://github.com/openconfig/featureprofiles/pull/1933/files#diff-446a8de58a33efff05bd4b6a8f500e980eb8aac9e163e869a2b62fc483054cc8L480)
- This comment is no longer valid: https://github.com/openconfig/featureprofiles/pull/1933/files#diff-446a8de58a33efff05bd4b6a8f500e980eb8aac9e163e869a2b62fc483054cc8L479

2023-08-24 01:31 UTC, octpetre commented on feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go
Done

2023-08-24 17:54 UTC, jasdeep-hundal approved these changes

2023-08-24 18:22 UTC, jasdeep-hundal commented
@ANISH-GOTTAPU : Please address the CLA status check (I'm guessing you used a different email here for a commit.)

2023-08-25 10:51 UTC, ANISH-GOTTAPU commented
> @ANISH-GOTTAPU : Please address the CLA status check (I'm guessing you used a different email here for a commit.)

@jasdeep-hundal : I used the same email ID, but I updated the branch from the web. However, when I commit something from the command line, the CLA status check passes.

2023-08-25 17:58 UTC, jasdeep-hundal approved these changes

2023-08-25 17:59 UTC, jasdeep-hundal commented
@ANISH-GOTTAPU or @octpetre : Please rebase once more.

2023-08-25 21:37 UTC, jasdeep-hundal commented
> @ANISH-GOTTAPU or @octpetre : Please rebase once more.

@ANISH-GOTTAPU / @octpetre : Please grant reviewers write access to the branch if you can, that would enable me to sync to latest/merge into main much quicker.

2023-08-25 21:44 UTC, merged