Align OTG test RT5.1 with ATE test
openconfig/featureprofiles pull request #2065
Opened 2023-08-28 09:51 UTC by ANISH-GOTTAPU

The PR Aligns the test RT5.1 with ATE test and resolves the below comment 

•	Missing breakout related testing

2023-08-29 16:12 UTC, marcushines commented
/fptest virtual

2023-09-07 23:51 UTC, jasdeep-hundal requested changes

2023-09-07 23:51 UTC, jasdeep-hundal commented on feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
@ANISH-GOTTAPU : Please replace the contents of the wait for ARP functions (https://github.com/openconfig/featureprofiles/pull/2065/files#diff-d1315065548f121c0e5eb7758b6bbb2e995fab646ad93d592dd61f8fd484a83cR362-R372) with an invocation to the otgutils method instead. (We're seeing some issues when we don't validated that _all_ neighbors are up.)

2023-09-08 13:25 UTC, ANISH-GOTTAPU commented on feature/interface/singleton/otg_tests/singleton_test/singleton_test.go
replaced with otgutils method

2023-09-08 15:32 UTC, jasdeep-hundal approved these changes

2023-09-08 15:33 UTC, merged