Add clarifications in new test requirements template
openconfig/featureprofiles pull request #2067
Opened 2023-08-28 23:53 UTC by dplore

2023-08-29 13:42 UTC, rszarecki commented
I will keep section to list minimum required DUT platform - MFF, FFF, vRx/KNE. Or expand metadata.textproto with this.

Also topology required would be handy for reader. But since this is covered by metadata file, not required, and would pose risk of inconsistency. So I do not know.

I personally would like this closer to top, perhaps before subtlest, as it defines environment/testbed.

2023-09-08 03:19 UTC, rszarecki requested changes

2023-09-08 16:28 UTC, dplore commented on tools/doc/test-requirements-template.md
> +* Specify the .testbed topology file from the //topologies folder to be used with this test
Added hyperlink.

Note, making the readme machine parsable is not a goal.  The readme is specifically for people to read.   The don't have CI checks for readme formatting (at least not yet).   We do have metadata.textproto available as one of the ways to add machine readable data per test, in addition to the test code itself of course.  We currently don't have any requirement for a readme to also include metadata.textproto.  (In fact, at the moment, generating metadata.textproto requires a readme to already be present)

2023-09-08 17:28 UTC, rszarecki approved these changes

2023-09-09 05:22 UTC, closed without merging