added MACs
openconfig/featureprofiles pull request #2080
Opened 2023-08-31 19:04 UTC by manan-patel

Mac entries were removed in PR
https://github.com/openconfig/featureprofiles/pull/1855/files#diff-8acaeb616dcb7318148a8e7c202fb4ffc7e4c7aaf98c5a59a9ed34d410583dfd

2023-08-31 21:09 UTC, jasdeep-hundal requested changes
atePort4 also needs a MAC address set

2023-09-11 20:37 UTC, jasdeep-hundal requested changes
@manan-patel : The condition here is inverted as compared to the ATE version: https://github.com/openconfig/featureprofiles/pull/2080/files#diff-8acaeb616dcb7318148a8e7c202fb4ffc7e4c7aaf98c5a59a9ed34d410583dfdL485

2023-09-12 00:25 UTC, manan-patel reviewed
I have updated the deviation to match with ATE tc. It should be skipped for all the vendors. It will fail for us due to traffic issue which keysights folks needs to help triage.

2023-09-14 19:30 UTC, jasdeep-hundal requested changes

2023-09-14 19:30 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Updated pMAC filters are not used in the OTG version: https://github.com/openconfig/featureprofiles/pull/1855/files#diff-9e7dc88076e3049421fead24f15eb32d877e829bc2df91eac7e5a61bb9edca81R48-R51

The verifyTrafficFlows function also needs to be updated for the OTG version of the test.

2023-09-14 19:30 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
The deleteinterfaceconfig message in the ATE test does not append the '0' to the interface name:
https://github.com/openconfig/featureprofiles/pull/1855/files#diff-9e7dc88076e3049421fead24f15eb32d877e829bc2df91eac7e5a61bb9edca81R808-R810

(This may be a fix for the ATE version of the test.)

2023-09-14 19:30 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
Need to move the configureATE call to be per test case. (That function resets the OTG config, and if we don't do that we end up trying to add duplicated flows.)

2023-09-14 19:30 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
> +	args.ate.OTG().StartProtocols(t)
Can add `otgutils.WaitForARP(t, args.ate.OTG(), args.top, "IPv4")` after this instead of waitOTGARPEntry.

2023-09-14 19:30 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/base_hierarchical_nhg_update/base_hierarchical_nhg_update_test.go
The waitOTGARPEntry function can be removed. (And current usages deleted, the usage at https://github.com/openconfig/featureprofiles/pull/2080/files#diff-8acaeb616dcb7318148a8e7c202fb4ffc7e4c7aaf98c5a59a9ed34d410583dfdR303 is extraneous.)

2023-09-19 23:48 UTC, jasdeep-hundal requested changes
We should rewrite the `getLossPct` function slightly because floating point math can get weird and we're sometimes seeing an incorrect non-zero output here. Casting should be deferred until the final computation, which should then become float32(loastPackets * 100) / float32(txPackets)

A few more changes requested in the comments as well.

2023-09-22 15:52 UTC, manan-patel commented
Raised PR https://github.com/openconfig/featureprofiles/pull/2172 to fix the CLA CI/CD check failing under current PR

2023-09-22 19:02 UTC, jasdeep-hundal commented
Merged in https://github.com/openconfig/featureprofiles/pull/2172 instead

2023-09-22 19:02 UTC, closed without merging