add authz helpers
openconfig/featureprofiles pull request #2100
Opened 2023-09-07 05:48 UTC by mojiiba

This pull add helper to populate rpc paths related to fp tests to simplify testing authz.

2023-09-08 04:30 UTC, harishkumar3091 commented on internal/security/authz/authz.go
> +		rule.Name = rule.Name + rpc.FQN
I believe this is QFN perhaps ?

2023-10-30 20:40 UTC, xw-g commented
I think this PR can be closed. https://github.com/openconfig/featureprofiles/pull/2136 includes all the changes of this PR. And I have already reviewed #2136

2023-10-31 19:30 UTC, greg-dennis requested changes

2023-10-31 19:30 UTC, greg-dennis commented on internal/security/gnxi/rpcs.go
> +	ALL                                                                   *RPC
Go style is to _not_ put these in all caps. Also, do the fields need to be exported here?

2023-10-31 19:30 UTC, greg-dennis commented on internal/security/gnxi/rpcexec.go
> +// function AllRPC implements a sample request for service * to validate if authz works as expected.
function comments should start with the name of the function, e.g. "AllRPC implements ..."

2023-11-23 05:45 UTC, closed without merging