gNMI-1.13: New deviation for transceiver thresholds
openconfig/featureprofiles pull request #2122
Opened 2023-09-13 17:24 UTC by sgirishj

Adding a new deviation for unsupported 'thresholds' container under transceiver component.

2023-09-14 17:10 UTC, sachendras submitted a review, later dismissed

2023-09-14 17:14 UTC, greg-dennis requested changes
Where are the changes to metadata.proto to go along with this deviation?

2023-09-14 17:16 UTC, sachendras commented
> Where are the changes to metadata.proto to go along with this deviation?

Is this not the one? https://screenshot.googleplex.com/6wgdxuxQs67cxPS

2023-09-14 17:36 UTC, sgirishj commented
> Where are the changes to metadata.proto to go along with this deviation?

Had left it out by mistake; just pushed it in. Thanks!

2023-09-15 03:28 UTC, greg-dennis approved these changes

2023-09-15 06:08 UTC, merged