Rszarecki st counters no gaps
openconfig/featureprofiles pull request #2147
Opened 2023-09-19 18:28 UTC by rszarecki

2023-09-19 21:30 UTC, dplore approved these changes

2023-09-19 21:33 UTC, dplore approved these changes
LGTM, some formatting comments and small question on sub test 2

2023-09-19 21:33 UTC, dplore commented on feature/interface/singleton/otg_tests/singleton_test/README.md
> +      * `/interfaces/interface[name=Port1]/state/counters/in-octets`
any reason these are not the same at Test case 3?

2023-09-19 21:33 UTC, dplore commented on feature/interface/singleton/otg_tests/singleton_test/README.md
> +### Test Case 1
```suggestion
### Sub Test 1
```

2023-09-19 21:33 UTC, dplore commented on feature/interface/singleton/otg_tests/singleton_test/README.md
> +## Test Case 2 [TODO: https://github.com/openconfig/featureprofiles/issues/2148]
```suggestion
### Sub Test 2 [TODO: https://github.com/openconfig/featureprofiles/issues/2148]
```

2023-09-19 21:33 UTC, dplore commented on feature/interface/singleton/otg_tests/singleton_test/README.md
> +## Test Case 3 [TODO: https://github.com/openconfig/featureprofiles/issues/2148]
```suggestion
### Sub Test 3 [TODO: https://github.com/openconfig/featureprofiles/issues/2148]
```

2025-02-04 07:52 UTC, ram-mac requested changes

2025-02-04 07:52 UTC, ram-mac commented on feature/interface/singleton/otg_tests/singleton_test/README.md
> +* Generate IPv4 and IPv6  traffic flow of packet size 4000B and IPv4 Don't Fragment bit set,  from ATE port-1 to ATE port-2 at constant rate, ensure:
1) With the ipv4 dont fragment bit set. The traffic is going to be dropped in the router and there will be a icmp packet will be sent back to the source. Please add verification of the ICMP message here.
2) We are testing only the default mtu 1500, can we also try to set the mtu at 9000 jumbo frame and send packet of size 9100 to check if this also is dropped at the router and verified?

2025-03-26 13:59 UTC, rszarecki commented on feature/interface/singleton/otg_tests/singleton_test/README.md
> +* Generate IPv4 and IPv6  traffic flow of packet size 4000B and IPv4 Don't Fragment bit set,  from ATE port-1 to ATE port-2 at constant rate, ensure:
The MTU is not subject of this test. But why not? Changed to 9k.
Also good catch on ICMP. However Subject of this test are counters not ICMP handling of too large packtetd w/ don't fragment bit. So, no ICMP verification in scope of this test.

2025-03-26 14:06 UTC, ram-mac commented on feature/interface/singleton/otg_tests/singleton_test/README.md
> +* Generate IPv4 and IPv6  traffic flow of packet size 4000B and IPv4 Don't Fragment bit set,  from ATE port-1 to ATE port-2 at constant rate, ensure:
Thanks

2025-03-26 14:09 UTC, merged