Adding interface passive state deviation
openconfig/featureprofiles pull request #2213
Opened 2023-10-05 16:57 UTC by divyarema

2023-10-05 19:17 UTC, greg-dennis requested changes

2023-10-05 19:17 UTC, greg-dennis commented on internal/deviations/deviations.go
> +func IsisInterfacePassiveStateUnsupported(dut *ondatra.DUTDevice) bool {
"Isis" -> "ISIS"

2023-10-06 17:27 UTC, divyarema commented on internal/deviations/deviations.go
> +func IsisInterfacePassiveStateUnsupported(dut *ondatra.DUTDevice) bool {
modified in latest commit

2023-10-17 19:37 UTC, arulkumarsekar commented
/gcbrun

2023-10-31 18:34 UTC, mohanasm commented
Closing as this change is no longer required.

2023-10-31 18:34 UTC, closed without merging