gNMI-1.19 ConfigPull after Control Card switchover (extending existing README.md)
openconfig/featureprofiles pull request #2452
Opened 2023-12-05 20:16 UTC by rszarecki

Adding sub-testcase 2  -  verifies if a large config can be pulled via gNMI GetRequest within 2 minutes after Control Card switchover.

2025-03-03 07:53 UTC, Swetha-haridasula commented
@rszarecki can we get the branch updated and errors resolved.

2025-03-18 11:10 UTC, singhavnish2516 requested changes

2025-03-18 11:10 UTC, singhavnish2516 commented on feature/platform/controllercard/tests/SetRequest_GetRequest_controll_card_switchover/README.md
>    * 800 Ethernet interfaces as member s of LAG
Hi @rszarecki, I think it is not feasible/possible to build configuration with such big numbers. For eg, 800 ethernet interfaces won't be available on most devices, specially in the test environment. Also, the RPC will fail to send this config due to `ResourceExhausted` type of errors. I think a valid ask would be to best utilize the maximum ports available in the device under test.

2025-03-18 11:10 UTC, singhavnish2516 commented on feature/platform/controllercard/tests/SetRequest_GetRequest_controll_card_switchover/README.md
> -# gNMI-1.19 ConfigPush after Control Card switchover
Can you please proof-read the README and correct the spelling/syntactical errors wherever applicable?

2025-03-18 11:10 UTC, singhavnish2516 commented on feature/platform/controllercard/tests/SetRequest_GetRequest_controll_card_switchover/README.md
> -# gNMI-1.19 ConfigPush after Control Card switchover
Open to discussion: I think the directory name should be `feature/platform/controllercard/tests/SetRequest_GetRequest_controller_card_switchover/`. Since we are anyways changing the directory structure as part of this PR, let's make this change?

2025-03-27 05:51 UTC, Swetha-haridasula approved these changes
lgtm

2025-03-27 05:52 UTC, self-maurya approved these changes

2025-03-27 05:54 UTC, merged