Kne link flap
openconfig/featureprofiles pull request #2542
Opened 2024-01-12 08:40 UTC by abhijit-dhar

feature/gribi/otg_tests/ipv4_entry_test/ipv4_entry_test.go has been changed. Due to addition of the feature kne link flap this test needs to be changed. Main chaange is there should not be any set config/push config call after link flap has been triggered.

2024-01-21 19:50 UTC, jasdeep-hundal requested changes

2024-01-22 17:00 UTC, jasdeep-hundal requested changes

2024-01-22 17:00 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/weighted_balancing_test/port_flap_rebalanced_test.go
@abhijit-dhar : This still needs to be addressed.

2024-01-22 17:32 UTC, abhijit-dhar commented on feature/gribi/otg_tests/weighted_balancing_test/port_flap_rebalanced_test.go
Hi Jasdeep, there are several file where this deviation exists. Can you please merge this PR with the deviation  ATEPortLinkStateOperationsUnsupported there? Then later we can log a separate PR with a request to remove all such deviations after merging this PR.

2024-01-22 19:03 UTC, jasdeep-hundal commented on feature/gribi/otg_tests/weighted_balancing_test/port_flap_rebalanced_test.go
@abhijit-dhar : Happy to defer these changes. Please sign the CLA and I can get this merged as-is.

2024-01-23 19:26 UTC, jasdeep-hundal requested changes
@abhijit-dhar : Actually needs formatting fixes as well (should just need to run `gofmt` on the files).

2024-01-24 18:56 UTC, closed without merging

2024-01-24 18:56 UTC, jasdeep-hundal commented
Closed in favor of https://github.com/openconfig/featureprofiles/pull/2573