RT-1.32: BGP policy actions - MED, LocPref, prepend, flow-control
openconfig/featureprofiles pull request #2616
Opened 2024-02-02 18:11 UTC by rszarecki

Test to validate BGP actions: MED

2024-02-02 23:35 UTC, dplore requested changes

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Set default import and export policy to ```REJECT_ROUTE```
```suggestion
*   Set default import and export policy to `REJECT_ROUTE`.   (Note: even though this is the OC default, the DUT should still accept this configuration)

```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Apply policy as import and export as a chain/list ```[med-policy]```
```suggestion
*   Add `policy-definition["med-policy"]` to import-policy and export-policy leaf-lists.
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Verify that there is no policies applied to the DUT BGP neighbor on ATE Port-2 and default policies are set to ```ACCEPT_ROUTE```
```suggestion
*   Verify that there are no policies applied to the DUT BGP neighbor on ATE Port-2 and default policies are set to ```ACCEPT_ROUTE```
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Apply policy as import and export as a chain/list ```[med-policy]```
```suggestion
*   Add `policy-definition["med-policy"]` to import-policy and export-policy leaf-lists.
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +        * Local Preference = 50
I suggest clarifying that the ATE is setting these BGP attributes (vs. the DUT which is what is done in the tests below).

```suggestion
    *   Advertise ```ipv4-network-2 = 192.168.20.0/24``` and ```ipv6-network-2 = 2024:db8:64:64::/64``` from ATE to DUT over the IPv4 and IPv6 eBGP session on port-2.  The ATE should advertise both prefixes with:
        * MED = 50
        * Local Preference = 50
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Apply policy as import and export as a chain/list ```[med-policy]```
```suggestion
*   Add `policy-definition["med-policy"]` to import-policy and export-policy leaf-lists.
* ```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Apply policy as import and export as a chain/list ```[med-policy]```
```suggestion
*   Add `policy-definition["med-policy"]` to import-policy and export-policy leaf-lists.
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Apply as import and export only policy - ```[lp-policy]```
```suggestion
*   Add `policy-definition["lp-policy"]` to import-policy and export-policy leaf-lists.
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Apply as import and export only policy - ```[lp-policy]```
```suggestion
*    Add `policy-definition["lp-policy"]` to import-policy and export-policy leaf-lists.
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +    *   /routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/repead-n
```suggestion
    *   /routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/repeat-n
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +    *   /routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/repead-n
```suggestion
    *   /routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/repeat-n
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +    *   /routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/repead-n
```suggestion
    *   /routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-as-path-prepend/config/repeat-n
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Validate that the ATE receives the prefix ```ipv6-network-2```  from DUT neighbor on ATE Port-1 and it has 11 ASN on as-path. First equial to ATE port-2 ASN and other 10 equal to ```23456``` ASN.
```suggestion
*   Validate that the ATE receives the prefix ```ipv4-network-1```  from DUT neighbor on ATE Port-2 and it has 11 ASN on as-path. First 10 equal to ```23456``` and last equal to DUT's ASN.
*   Validate that the ATE receives the prefix ```ipv6-network-1```  from DUT neighbor on ATE Port-2 and it has 11 ASN on as-path. First 10 equal to ```23456``` and last equal to DUT's ASN.
*   Validate that the ATE receives the prefix ```ipv4-network-2```  from DUT neighbor on ATE Port-1 and it has 11 ASN on as-path. First equal to ATE port-2 ASN and other 10 equal to ```23456``` ASN.
*   Validate that the ATE receives the prefix ```ipv6-network-2```  from DUT neighbor on ATE Port-1 and it has 11 ASN on as-path. First equal to ATE port-2 ASN and other 10 equal to ```23456``` ASN.
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +*   Validate that the ATE receives the prefix ```ipv6-network-2```  from DUT neighbor on ATE Port-1 and it has 11 ASN on as-path. First equial to ATE port-2 ASN and other 10 equal to ```23456``` ASN.
```suggestion
*   Validate that the ATE receives the prefix ```ipv4-network-1```  from DUT neighbor on ATE Port-2 and it has 11 ASN on as-path. First 10 equal to ```23456``` and last equal to DUT's ASN.
*   Validate that the ATE receives the prefix ```ipv6-network-1```  from DUT neighbor on ATE Port-2 and it has 11 ASN on as-path. First 10 equal to ```23456``` and last equal to DUT's ASN.
*   Validate that the ATE receives the prefix ```ipv4-network-2```  from DUT neighbor on ATE Port-1 and it has 11 ASN on as-path. First equal to ATE port-2 ASN and other 10 equal to ```23456``` ASN.
*   Validate that the ATE receives the prefix ```ipv6-network-2```  from DUT neighbor on ATE Port-1 and it has 11 ASN on as-path. First equal to ATE port-2 ASN and other 10 equal to ```23456``` ASN.
```

2024-02-02 23:35 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +  * Set
```suggestion
  * Subscribe (ONCE)
  * Set (REPLACE)
```

2024-02-03 00:15 UTC, rszarecki commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +
I do not know if this is safe, as it impacts interface configuration. Hence can effectivly remove management access.

Instead I add above instruction under each tets, when configuration modifies only policy tree.

2024-02-03 00:54 UTC, dplore commented on feature/bgp/policybase/otg_tests/actions-MED_LocPref_prepend_flow-control/README.md
> +> WARNING: Ensure that replacement do not remove pre-existing configuration objects necessary for DUT manage,ent access and base operation.
```suggestion
> WARNING: Replace operations should be performed at an appropriate level in the config tree to ensure that preexisting configuration objects necessary for DUT management access and base operation are not removed.
```

2024-02-03 00:55 UTC, dplore approved these changes
One last suggestion regarding the warning on gnmi replace

2024-02-03 01:19 UTC, dplore approved these changes

2024-02-03 01:45 UTC, merged