Adding a 400ZR test for ZR supply voltage.
openconfig/featureprofiles pull request #2620
Opened 2024-02-05 01:12 UTC by ahsaanyousaf

Adding a 400ZR test for ZR supply voltage.

2024-02-05 23:11 UTC, dplore commented on feature/platform/transceiver/zr_supply_voltage_test/README.md
> +
Add test topology header

2024-02-05 23:15 UTC, dplore requested changes

2024-02-05 23:15 UTC, dplore commented on feature/platform/transceiver/zr_supply_voltage_test/README.md
> +    *   /platform/components/component/state/supply-voltage/avg
/components/component/transceiver/state/supply-voltage	

```suggestion
    *   /components/component/transceiver/state/supply-voltage/instant
    *   /components/component/transceiver/state/supply-voltage/min
    *   /components/component/transceiver/state/supply-voltage/max
    *   /components/component/transceiver/state/supply-voltage/avg
```

2024-02-05 23:15 UTC, dplore commented on feature/platform/transceiver/zr_supply_voltage_test/README.md
> +*   /platform/components/component/state/supply-voltage/avg
```suggestion
    *   /components/component/transceiver/state/supply-voltage/instant
    *   /components/component/transceiver/state/supply-voltage/min
    *   /components/component/transceiver/state/supply-voltage/max
    *   /components/component/transceiver/state/supply-voltage/avg
```

2024-02-06 03:13 UTC, ahsaanyousaf commented on feature/platform/transceiver/zr_supply_voltage_test/README.md
> +
Done

2024-02-06 19:55 UTC, dplore approved these changes

2024-02-06 19:56 UTC, merged