Add System base and NTP config libraries
openconfig/featureprofiles pull request #266
Opened 2022-06-23 14:06 UTC by sthesayi

Add System base and NTP config libraries.

2022-06-24 14:41 UTC, robshakir requested changes

2022-06-24 14:42 UTC, robshakir commented
@sthesayi @bstoll -- it'd be good to collaborate with Brandon going forward on the library here, I think we want to make sure that the API that we build here groups this in the 'logical' way for the use cases we have. Brandon, is this something that you might have to cycles to help with?

2022-06-24 18:12 UTC, sthesayi commented on feature/system/system.go
> +func (s *System) WithUserAuth(username, sshkey string) *System {
This would be tricky. How about we create different APIs for adding user, say one with key and another with password?

2022-06-24 18:22 UTC, sthesayi commented on feature/system/ntp/ntp.go
> +func (n *NTP) WithServer(address string, port int) *NTP {
Yes Rob, this is correct pattern to have. Thanks for catching that. I will fix others that may be incorrect.

2022-06-24 18:23 UTC, sthesayi commented
> 

I agree. I will loop in Brandon in these reviews.

2022-06-28 17:20 UTC, bstoll approved these changes
This LGTM.  I am certain that AAA/user management will need to be refactored out of the "system base" feature profile - it is quite complex by itself.  I don't know if that needs to change this PR - what is implemented here is what is defined in the feature profile.

2022-06-29 14:56 UTC, merged