GNMI 1.4 Optic Temperature Sensor Test
openconfig/featureprofiles pull request #2697
Opened 2024-02-21 20:59 UTC by mastarkey

Added the following changes 

# GNMI Feature Request
openconfig-platform:components/component/state/temperature/instant
openconfig-platform:components/component/state/temperature/avg
openconfig-platform:components/component/state/temperature/min
openconfig-platform:components/component/state/temperature/max
openconfig-platform:components/component/state/temperature/min-time
openconfig-platform:components/component/state/temperature/max-time
openconfig-platform:components/component/state/temperature/interval

2024-02-22 07:18 UTC, AmrNJ commented
Hi @mastarkey, Please can you update the label for this PR. Also I don't see these OC paths requested. Is there a feature request for this?

2024-02-27 05:35 UTC, AmrNJ commented
Please can you rebase?

2024-03-04 05:59 UTC, AmrNJ requested changes
May I know who requested for this OC leaf? These paths are not present in the supported list of wbb paths.

2026-08-18 18:37 UTC, karthikeya-remilla commented
Obsolete PR. Closing this.

2026-08-18 18:37 UTC, closed without merging