TE-16.2 Encap Frr Test - fix for using l2 rules and sequenceID
openconfig/featureprofiles pull request #2889
Opened 2024-04-10 11:28 UTC by suredhar

1. Added back code to use deviation for default class by using L2 rules.
2. Added a function to generate sequence IDs off a base value to avoid out-of-order rule sequences in a policy-map configuration.
3. Added a deviation for the gRIBI IPv4 route. The device does not support a MAC address, only a next-hop entry.
4. Added the following deviations:
    -> gribi_mac_override_with_static_arp
    -> interface_ref_interface_id_format
   -> pf_require_match_default_rule

2024-04-19 07:35 UTC, AmrNJ requested changes
Fails at speed setting.

2024-05-23 12:49 UTC, NishaSadhasivam-work approved these changes
LGTM!

2024-05-23 12:49 UTC, NishaSadhasivam-work commented on feature/gribi/otg_tests/encap_frr/encap_frr_test.go
> +func programAftWithDummyIp(t *testing.T, dut *ondatra.DUTDevice, args *testArgs) {
rename programAftWithDummyIp to programAftWithDummyIP

2024-05-23 12:49 UTC, NishaSadhasivam-work commented on feature/gribi/otg_tests/encap_frr/encap_frr_test.go
> +		programAftWithDummyIp(t, dut, args)
rename programAftWithDummyIp to programAftWithDummyIP

2024-05-26 09:13 UTC, NishaSadhasivam-work approved these changes
LGTM!

2024-05-27 03:47 UTC, AmrNJ approved these changes

2024-05-27 04:11 UTC, merged