RT-1.14: Added code to proceed with BGP based on interface status.
openconfig/featureprofiles pull request #2902
Opened 2024-04-17 05:52 UTC by mohanasm

Updated code to proceed with BGP config based on interface status.

2024-07-25 03:37 UTC, LimeHat requested changes

2024-07-25 03:37 UTC, LimeHat commented on feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
> +			portDownCnt++
It seems that replacing `t.Error()` with `t.Fatal()` is the easier approach if you want to stop the test when a port is not up. No need to introduce additional counters and propagate that state.

2024-07-25 03:37 UTC, LimeHat commented on feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
> +			if len(ateIntfList) > 0 {
From what I see, `ateIntfList` is initialized only once during the test execution and not modified after that. Why do we need multiple additional checks on this variable?

2025-01-27 05:01 UTC, mohanasm commented on feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
> +			portDownCnt++
Agree with you. Updated the file.

2025-01-27 05:01 UTC, mohanasm commented on feature/experimental/bgp/ate_tests/bgp_long_lived_graceful_restart/bgp_long_lived_graceful_restart_test.go
> +			if len(ateIntfList) > 0 {
Not needed and removed it.

2025-05-08 05:49 UTC, ram-mac approved these changes
Changes looks good

2025-05-09 08:14 UTC, rohit-rp approved these changes

2025-05-09 09:19 UTC, merged