RT-7.5 : link_bandwidth_test
openconfig/featureprofiles pull request #2907
Opened 2024-04-19 05:22 UTC by cprabha

BGP Peer group is required for neighbor ,  similar to other BGP tests.

2024-07-23 04:00 UTC, nsadhasivam requested changes

2024-07-23 04:00 UTC, nsadhasivam commented on proto/metadata.proto
> +    bool policy_result_type_next_statement_unsupported = 175;
if this deviation is really needed, we can use skip_setting_statement_for_policy

2024-08-20 19:09 UTC, cprabha commented on feature/experimental/bgp/otg_tests/link_bandwidth_test/link_bandwidth_test.go
> +							verifyExtCommunityIndexV4(t, td, v4Prefix)
@nsadhasivam BGP loc rib is not supported and if i move inside the function, we will need to skip entire code.

2024-08-20 19:10 UTC, cprabha commented on feature/experimental/bgp/otg_tests/link_bandwidth_test/link_bandwidth_test.go
> +		validateImportRoutingPolicyAllowAll(t, td.dut, td.ate)
@nsadhasivam BGP loc rib is not supported and if i move inside the function, we will need to skip entire code.

2025-01-28 19:33 UTC, cprabha commented on feature/experimental/bgp/otg_tests/link_bandwidth_test/link_bandwidth_test.go
> +	if deviations.PolicyResultTypeNextStatementUnsupported(dut) {
updated script, plz chk

2025-01-28 19:33 UTC, cprabha commented on proto/metadata.proto
> +    bool policy_result_type_next_statement_unsupported = 175;
updated script

2025-04-22 04:22 UTC, AmrNJ commented
The code doesn't pass. 
 [edit groups junos-yang policy-options community linkbw_1M]
        ;
        Unknown extended community type
        ;
        configuration check-out failed

2025-04-23 13:10 UTC, AmrNJ submitted a review, later dismissed

2025-04-23 13:31 UTC, ram-mac requested changes

2025-04-23 13:31 UTC, ram-mac commented on feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
> +	gnmi.Update(t, dut, gnmi.OC().RoutingPolicy().Config(), rp)
@cprabha - Here we are using gnmi.Update instead of gnmi.Replace
Below the README specifies to use Set REPLACE for both import and export policy. Can you explain?

Use gnmi Set REPLACE option for:

/routing-policy/policy-definitions to configure the policy
Use /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/afi-safis/afi-safi/apply-policy/config/import-policy to apply the policy on the DUT bgp neighbor to the ATE port 1.

2025-04-29 22:19 UTC, cprabha commented on feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
> +	gnmi.Update(t, dut, gnmi.OC().RoutingPolicy().Config(), rp)
updated to gnmi replace operation

2025-05-05 06:05 UTC, AmrNJ approved these changes

2025-05-05 08:46 UTC, ram-mac approved these changes
After the changes, LGTM.

Approved!

2025-05-05 08:51 UTC, rohit-rp approved these changes

2025-05-05 17:52 UTC, merged