Remove isis_lsp_lifetime_interval_requires_lsp_refresh_interval deviation
openconfig/featureprofiles pull request #2983
Opened 2024-05-11 05:54 UTC by yini101

Remove isis_lsp_lifetime_interval_requires_lsp_refresh_interval deviation from:

1. proto/metadata.proto
2. feature/experimental/isis/otg_tests/isis_interface_passive_test/metadata.textproto
3. feature/experimental/isis/otg_tests/isis_interface_level_passive_test/metadata.textproto
4. feature/experimental/isis/otg_tests/isis_metric_style_wide_not_enabled_test/metadata.textproto
5. feature/experimental/isis/otg_tests/isis_interface_hello_padding_enable_test/metadata.textproto
6. feature/experimental/isis/otg_tests/isis_change_lsp_lifetime_test/metadata.textproto

2024-05-12 17:39 UTC, nandanarista requested changes
Hi Yini, we also need to remove the function that queries the deviation and its callers

https://github.com/search?q=repo%3Aopenconfig%2Ffeatureprofiles%20isislsplifetimeintervalrequireslsprefreshinterval&type=code

2025-01-30 04:32 UTC, self-maurya approved these changes

2025-01-30 04:33 UTC, self-maurya approved these changes

2025-01-30 05:18 UTC, rohit-rp approved these changes

2025-01-30 05:20 UTC, merged