GNMI-2: gnmi_subscriptionlist_test
openconfig/featureprofiles pull request #2996
Opened 2024-05-17 13:59 UTC by hattikals

- Resolves #2390

2024-08-30 15:12 UTC, Swetha-haridasula requested changes

2024-09-02 03:59 UTC, hattikals commented on feature/gnmi/subscribe/tests/gnmi_subscriptionlist_test/gnmi_subscriptionlist_test.go
> +			gnmi.OC().InterfaceAny().ForwardingViable().State().PathStruct(),
Added at line number 77. As backplaneCapacity is supported only when number of controller cards is greater than 0.

2024-09-02 03:59 UTC, hattikals commented on feature/gnmi/subscribe/tests/gnmi_subscriptionlist_test/gnmi_subscriptionlist_test.go
> +		},
Added at line number 77. As backplaneCapacity is supported only when number of controller cards is greater than 0.

2024-09-02 08:29 UTC, Swetha-haridasula approved these changes
LGTM

2024-09-02 08:50 UTC, merged