RT-1.23 BGP AFI SAFI OC DEFAULTS TEST changes incorporated.
openconfig/featureprofiles pull request #3146
Opened 2024-06-28 08:19 UTC by ampattan

-Changes in metadata.textproto

  -explicit_interface_in_default_vrf
  -bgp_global_extended_next_hop_encoding_unsupported
  -skip_bgp_session_check_without_afisafi

-Changes in bgp_afi_safi_defaults_test.go

  -Removed unused ports from verifyPortsUp func.
  -Enabled global AFI-SAFI configuration.
  -Unsetting IPV4 AFI-SAFI flag under nieghbour level
  -Added deviation ExplicitInterfaceInDefaultVRF, BGPGlobalExtendedNextHopEncodingUnsupported

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

2024-09-04 07:29 UTC, nsadhasivam requested changes

2024-09-04 07:29 UTC, nsadhasivam commented on feature/experimental/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
> +		ocName := dev.Port(t, p.Name).Name()
Why is this change needed? Is its specific to Nokia, Can we have it under a deviation?

2025-01-15 06:51 UTC, ampattan commented
HW log with these changes are available at - b/390070863

2025-01-22 07:09 UTC, nsadhasivam approved these changes
LGTM!

2025-01-22 08:54 UTC, ram-mac requested changes

2025-01-22 08:54 UTC, ram-mac commented on feature/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
> +	if isV4Only {
For IPv4 only ipv4 needs to be enabled and ipv6 should be left to the default OC path. These changes are not as per README. Take a look at the [PR](https://github.com/openconfig/featureprofiles/pull/3627/files); These changes are as per the README; pasting below the changes.


			if nbr.isV4 == true {
				global.GetOrCreateAfiSafi(oc.BgpTypes_AFI_SAFI_TYPE_IPV4_UNICAST).Enabled = ygot.Bool(true)
			} else {
				global.GetOrCreateAfiSafi(oc.BgpTypes_AFI_SAFI_TYPE_IPV6_UNICAST).Enabled = ygot.Bool(true)
			}

2025-01-22 08:54 UTC, ram-mac commented on feature/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
> +func verifyPortsUp(t *testing.T, dev *ondatra.Device, portList []string) {
@ampattan What is the need to add another argument to this function. We have already the dev.ports returning the list of ports. Shouldn't that be sufficient
Can you give some more clarification on this change

2025-01-24 05:33 UTC, ram-mac approved these changes

2025-01-24 05:36 UTC, nsadhasivam commented on feature/bgp/otg_tests/bgp_afi_safi_defaults/bgp_afi_safi_defaults_test.go
> +func verifyPortsUp(t *testing.T, dev *ondatra.Device, portList []string) {
Since it does not accept the feature coverage. resolving the issue

2025-01-27 07:58 UTC, nsadhasivam approved these changes
LGTM!

2025-01-27 10:22 UTC, rohit-rp approved these changes

2025-01-27 10:24 UTC, merged