fix aggregate_all_not_forwarding_viable_test
openconfig/featureprofiles pull request #3260
Opened 2024-07-12 11:18 UTC by nsadhasivam

2024-07-12 16:20 UTC, LimeHat commented
Please stop using this deviation for this code snippet, this is not correct as I indicated in
https://github.com/openconfig/featureprofiles/pull/2984#issuecomment-2108074887

Regarding this code snippet, I have an open issue #2977. If there's a vendor who needs it, it should be a new deviation. Otherwise, it should be removed altogether as proposed in #3153 

cc @dplore @cfernanz

2024-07-12 16:31 UTC, LimeHat requested changes

2024-07-12 16:31 UTC, LimeHat commented on feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
> +			if port.PMD() == ondatra.PMD100GBASEFR && deviations.ExplicitPortSpeed(dut) {
this is not a correct usage of the deviation

2024-07-16 16:00 UTC, nsadhasivam commented
> Please stop using this deviation for this code snippet, this is not correct as I indicated in [#2984 (comment)](https://github.com/openconfig/featureprofiles/pull/2984#issuecomment-2108074887)
> 
> Regarding this code snippet, I have an open issue #2977. If there's a vendor who needs it, it should be a new deviation. Otherwise, it should be removed altogether as proposed in #3153
> 
> cc @dplore @cfernanz

Hi Sergey, 

Have added explicit deviations for portspeed and duplex mode, is this what you are looking for?

2024-07-16 20:52 UTC, LimeHat commented
I believe `e.AutoNegotiate = ygot.Bool(false)` should also be under a deviation if there's a vendor that requires this config. 

Potentially, you can group all three things under a single deviation, `100g_fr_explicit_config` or something like that.

But again it is not clear if this is required at all. Discussion in #2977 didn't result in any findings in terms of ownership of this config. If there are no vendors who need it (nokia, cisco, and juniper don't, as far as I understand), then we should just remove it as proposed in #3153.

2024-07-16 21:01 UTC, LimeHat requested changes

2024-07-16 21:01 UTC, LimeHat commented on feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
> -		isisIntf.GetOrCreateInterfaceRef().Subinterface = ygot.Uint32(0)
why is this being removed? full ref (interface+subif) should be used here.

if an implementation doesn't support refs they should use a deviation (e.g. just below there's `if deviations.InterfaceRefConfigUnsupported(dut)` statement that can be used for them)

2024-07-16 21:01 UTC, LimeHat commented on feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
> +				}
the whole block should be under a new deviation if there's a vendor who needs it

2024-07-17 01:09 UTC, dplore commented
> I believe `e.AutoNegotiate = ygot.Bool(false)` should also be under a deviation if there's a vendor that requires this config.
> 
> Potentially, you can group all three things under a single deviation, `100g_fr_explicit_config` or something like that.
> 
> But again it is not clear if this is required at all. Discussion in #2977 didn't result in any findings in terms of ownership of this config. If there are no vendors who need it (nokia, cisco, and juniper don't, as far as I understand), then we should just remove it as proposed in #3153.

@nsadhasivam we think that this configuration should not be required.  

Are you finding that this is mandatory?  If yes, for which devices/vendors?  In concept, this config should not be needed.  If a certain vendor does need it, then it should be a deviation just for that vendor.

2024-07-17 16:24 UTC, LimeHat commented on feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
> -		isisIntf.GetOrCreateInterfaceRef().Subinterface = ygot.Uint32(0)
That shouldn't be the case

OC definition says:
```
In contexts
        where a Layer 3 interface is to be referenced, both the
        interface and subinterface leaves must be populated, as
        Layer 3 configuration within the OpenConfig models is
        associated with a subinterface.
```

https://github.com/openconfig/public/blob/0ae6953d5d0ee8156f48088ff7a1bb37ae0ce179/release/models/interfaces/openconfig-interfaces.yang#L228-L239

Bundles can also have subinterfaces, and you can see it is being configured on https://github.com/openconfig/featureprofiles/blob/99f8453fdaa2c47f9bffc41828cd16e5edece029/feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go#L452-L467 in this test.

The issue is that some vendors don't use proper subinterfaces and associate layer 3 information with the physical interface when you configure "subinterface 0", but it's not an OC-compliant way.

cc @dplore

2025-05-09 07:58 UTC, AmrNJ requested changes
Can you please resolve comments?

2025-07-08 06:37 UTC, closed without merging