Update testregistry.textproto
openconfig/featureprofiles pull request #3314
Opened 2024-07-20 13:38 UTC by sachendras

Updates is to include missing test RT-1.19 for 2-byte and 4-byte ASNs

2024-07-22 13:47 UTC, dplore requested changes

2024-07-22 13:47 UTC, dplore commented on testregistry.textproto
> +  exec: " "
missing a trailing `}`

2024-07-22 19:49 UTC, sachendras commented
/gcbrun

2024-07-22 20:41 UTC, sachendras commented on testregistry.textproto
> +  exec: " "
corrected

2024-07-23 00:24 UTC, dplore approved these changes

2024-07-23 00:43 UTC, merged