RT 1.24: Updated the script with default policy behavior for BGP external and internal neighbors
openconfig/featureprofiles pull request #3346
Opened 2024-07-30 19:09 UTC by s-nandu

RT 1.24: Updated the script with default policy behavior for BGP external and internal neighbors

2024-12-26 03:09 UTC, Swetha-haridasula commented
kindly resolve the conflicts and re-source file to latest location 'google3/third_party/openconfig/featureprofiles/feature/bgp/otg_tests/bgp_2byte_4byte_asn/'

2024-12-27 04:42 UTC, Swetha-haridasula commented
The branch has changed. Kindly update the branch and resolve conflicts

2025-01-09 07:13 UTC, ram-mac approved these changes
The changes looks good

2025-01-09 07:14 UTC, ram-mac requested changes
there are static analysis failures. These are mostly due to format issue.
Please fix it.

2025-02-10 07:13 UTC, ram-mac approved these changes

2025-02-11 16:44 UTC, rohit-rp approved these changes

2025-02-11 16:45 UTC, merged