added certz3.1
openconfig/featureprofiles pull request #3360
Opened 2024-08-03 04:08 UTC by priyacj

certz3.1 gNSI Server Certificate Rotation

2024-09-22 18:33 UTC, morrowc reviewed
there are some Check() fialure things to address here

2024-09-22 18:33 UTC, morrowc commented on feature/security/gnsi/certz/tests/internal/setup_service/setup_service.go
> +	} else {
do the thing in the Check failure comment please.
Generally 'just don't use else' is the advice for golang code.

2024-09-22 18:33 UTC, morrowc commented on feature/security/gnsi/certz/tests/internal/setup_service/setup_service.go
> +			if i == len(trust)-1 {
this looks like some special handling for the last  or first time through the loop, either document 'very well' why this is here or just do this whole thing in a way that doesn't require this check for every loop entry.

2024-12-04 21:15 UTC, morrowc reviewed
fix the static-analysis failures. please.

2025-11-04 02:59 UTC, morrowc commented on feature/gnsi/certz/tests/server_certificate_rotation/README.md
> -### Certz-3.2
what happened to this part?

2025-11-04 17:31 UTC, priyacj commented on feature/gnsi/certz/tests/server_certificate_rotation/README.md
> -### Certz-3.2
This testcase 3.2  is being removed based on discussion in b/311141278.

2025-11-05 16:33 UTC, morrowc approved these changes

2025-11-05 16:33 UTC, morrowc commented on feature/gnsi/certz/tests/server_certificate_rotation/README.md
> -### Certz-3.2
Ok, we actually have devices which require this behavior (or which fail to use a cert that can't be validated by the local trustbundle)

I suppose "sure that's not REQUIRED"

2025-11-05 20:08 UTC, mihirpitale-googler approved these changes
lgtm

2025-11-06 20:49 UTC, dplore commented
Hi @priyacj, please share test results.  This can be via a private issue you file at https://issuetracker.google.com or vist a [GitHub gist](https://gist.github.com/).

2025-11-06 20:50 UTC, dplore commented
/gemini review

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +package setupservice
```suggestion
package clientcertificatessetup
```

Or if you move to `/internal/security/certz/`,  then:
`package certz`

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
Since this package is only for the `client_certificates` test, then  perhaps file path should be 
`feature/gnsi/certz/tests/client_certificates/setup/setup.go`

if other certz tests might use this, then a better folder is:
`/internal/security/certz/`

(note there are already other test helpers in `/internal/security`)

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyGnoi(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
these should go in internal/gnoi/gnoi.go

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateGnoiPingRequest(ctx context.Context, t *testing.T, sysClient spb.SystemClient, mismatch bool) bool {
these should go in internal/gnoi/gnoi.go

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyGnmi(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
Should be moved to internal/gnmi I think

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateGnmiCapabilityRequest(ctx context.Context, t *testing.T, gnmiClient gnmipb.GNMIClient, mismatch bool) bool {
internal/gnmi

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyGribi(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
internal/gribi

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateGribiGetRequest(ctx context.Context, t *testing.T, gRibiClient gribipb.GRIBIClient, mismatch bool) bool {
internal/gribi

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyP4rt(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
internal/p4rtutils

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateP4RtCapabilitiesRequest(ctx context.Context, t *testing.T, p4rtClient p4rtpb.P4RuntimeClient, mismatch bool) bool {
internal/p4rtutils

2025-11-06 23:41 UTC, dplore commented on feature/gnsi/certz/tests/server_certificate_rotation/README.md
> +```json
```suggestion
## Canonical OC
No OC configuration is performed in this test as all interaction is via gNSI.Certz

```json
```

2025-11-14 15:37 UTC, ksgireesha commented
**Pre-merge Action**: @ram-mac  , kindly execute this test within our environment before merging. We can proceed with the merge upon successful test completion

2025-11-25 01:29 UTC, dplore requested changes
Please address the comments on this PR before it can be merged

2025-12-06 00:03 UTC, dplore commented
@priyacj please address the open comments

2026-02-10 04:40 UTC, dplore commented on feature/gnsi/certz/tests/server_certificate_rotation/README.md
> +```json
please address this comment

2026-02-10 04:40 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateP4RtCapabilitiesRequest(ctx context.Context, t *testing.T, p4rtClient p4rtpb.P4RuntimeClient, mismatch bool) bool {
please address this comment

2026-02-10 04:40 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyP4rt(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
please address this comment

2026-02-10 04:40 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateGribiGetRequest(ctx context.Context, t *testing.T, gRibiClient gribipb.GRIBIClient, mismatch bool) bool {
please address this comment

2026-02-10 04:40 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyGribi(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
please address this comment

2026-02-10 04:40 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyGnmi(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
please address this comment

2026-02-10 04:40 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateGnoiPingRequest(ctx context.Context, t *testing.T, sysClient spb.SystemClient, mismatch bool) bool {
please address this comment

2026-02-10 04:41 UTC, dplore commented
@priyacj please address the open comments so we can proceed with merging this PR.  Thanks!

2026-02-15 21:02 UTC, morrowc commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +	wg.Wait()
This looks like a good suggestion and fix.

2026-02-15 21:03 UTC, morrowc commented on feature/gnsi/certz/tests/server_certificate_rotation/server_certificate_rotation_test.go
> +	prevTrustBundleFile string          = ""
Shared state here is going to be a problem, eventually.
Please move the currently shared state into the test definitions / struct.

2026-02-15 21:03 UTC, morrowc commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +)
Fix this as well. I think this is the same sort of problem as the last.

2026-02-15 21:04 UTC, morrowc commented on feature/gnsi/certz/tests/server_certificate_rotation/server_certificate_rotation_test.go
> +	logTime             string          = time.Now().String() //Timestamp
I think you just need to move this logTime into each test loop so you get unique times per loop through in the logs.

2026-02-15 21:05 UTC, morrowc commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
Yes please.

2026-02-19 18:06 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +	wg.Wait()
This comment is still open, pelase resolve

2026-02-19 18:06 UTC, dplore commented on feature/gnsi/certz/tests/server_certificate_rotation/server_certificate_rotation_test.go
> +	prevTrustBundleFile string          = ""
@priyacj this needs to be addressed

2026-02-19 18:06 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +)
@priyacj please address

2026-02-19 18:06 UTC, dplore commented on feature/gnsi/certz/tests/server_certificate_rotation/server_certificate_rotation_test.go
> +	logTime             string          = time.Now().String() //Timestamp
@priyacj please address

2026-02-19 18:07 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +		time.Sleep(30 * time.Second) //waiting 30s for gnmi config propagation//
@priyacj please fix

2026-02-19 18:07 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +	target := fmt.Sprintf("%s:%d", serverAddr, 9339)
@priyacj please fix

2026-02-19 18:07 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +	return true
@priyacj please fix

2026-02-19 18:08 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +package setupservice
@priyacj please fix

2026-02-19 18:08 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
@priyacj please fix

2026-02-19 18:08 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyGnoi(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
@priyacj please fix

2026-02-19 18:08 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateGnoiPingRequest(ctx context.Context, t *testing.T, sysClient spb.SystemClient, mismatch bool) bool {
@priyacj please fix

2026-02-19 18:08 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyGnmi(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
@priyacj please fix

2026-02-19 18:08 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyGribi(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
@priyacj please fix

2026-02-19 18:08 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateGribiGetRequest(ctx context.Context, t *testing.T, gRibiClient gribipb.GRIBIClient, mismatch bool) bool {
@priyacj please fix

2026-02-19 18:08 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func VerifyP4rt(t *testing.T, caCert *x509.CertPool, san, serverAddr, username, password string, cert tls.Certificate, mismatch bool) bool {
@priyacj please fix

2026-02-19 18:09 UTC, dplore commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
> +func ValidateP4RtCapabilitiesRequest(ctx context.Context, t *testing.T, p4rtClient p4rtpb.P4RuntimeClient, mismatch bool) bool {
@priyacj please fix

2026-03-31 19:12 UTC, priyacj commented on feature/gnsi/certz/tests/server_certificate_rotation/README.md
> +```json
Addressed , please check

2026-04-14 19:49 UTC, dplore approved these changes

2026-04-14 19:50 UTC, dplore commented
/fptest virtual

2026-04-14 19:50 UTC, dplore commented
Thanks for all the changes @priyacj.  Please share a link to a log of the test results.  FYI: this is needed for every PR

2026-04-14 20:42 UTC, dplore commented
@priyacj note this test fails the kne/virtual environment.  At a minimum it seems like some required files are missing?
See 
[Log](https://storage.cloud.google.com/featureprofiles-ci-logs-juniper/log-365a0acf-25b9-41d2-915c-f35011d49db4.txt)

2026-04-14 20:43 UTC, dplore commented
@morrowc @mihirpitale-googler in future, please ensure test is producing expected results before approving. Thanks!

2026-04-14 20:44 UTC, dplore requested changes
please address comments regarding test logs and possibly missing dependencies

2026-05-15 22:17 UTC, dplore commented
/fptest virtual

2026-05-15 22:18 UTC, dplore commented
@priyacj note this test fails the kne/virtual environment. At a minimum it seems like some required files are missing?
See
[Log](https://storage.cloud.google.com/featureprofiles-ci-logs-juniper/log-365a0acf-25b9-41d2-915c-f35011d49db4.txt)

2026-06-12 06:20 UTC, ksgireesha commented
@priyacj  - Have you addressed, @dplore's [comment](https://github.com/openconfig/featureprofiles/pull/3360#issuecomment-4464198917) above?

2026-07-02 04:56 UTC, sudhirakondi commented
Task Created to track running Ondatra tests on the ncptx:
https://partnerissuetracker.corp.google.com/issues/507392581

Also, attached pass logs for the certz tests to above.

2026-07-02 05:50 UTC, ram-mac commented on feature/gnsi/certz/tests/internal/setup_service/setup_service.go
This seems to be taken care of now

2026-07-02 05:51 UTC, ram-mac commented
> @priyacj - Have you addressed, @dplore's [comment](https://github.com/openconfig/featureprofiles/pull/3360#issuecomment-4464198917) above?

I think this is now taken care of. The logs pointed out by Sudhir shows the test is passing in KNE environment.

2026-07-02 05:51 UTC, ram-mac approved these changes
LGTM

2026-07-02 13:06 UTC, merged