SFLOW-1: Configuring sflow collector respective to IPv4 and IPv6
openconfig/featureprofiles pull request #3471
Opened 2024-09-27 16:43 UTC by trathod1

Following changes are made -
   1. Removing explicit_interface_in_default_vrf, considering test is using non-default VRF mvrf1 for the interface.
   2. Based on discussion b/290965827, refactoring the sflow collector configurations to be part of respective V4 and V6 test.

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

2024-10-18 21:03 UTC, dplore commented
/fptest virtual

2024-12-27 04:35 UTC, nsadhasivam submitted a review, later dismissed
Thank you!
LGTM!

2024-12-27 04:44 UTC, self-maurya approved these changes

2025-01-02 20:34 UTC, dplore commented
/fptest virtual

2025-01-03 02:18 UTC, nsadhasivam approved these changes
LGTM!

2025-01-03 04:09 UTC, self-maurya requested changes

2025-01-03 04:09 UTC, self-maurya commented on internal/cfgplugins/sflow.go
> +		switch ip {
Can we something like below to reduce the code complexity:

```
var address, srcAddress string
switch ip {
    case "IPv4":
        address = "192.0.2.129"
        srcAddress = srcAddrV4
    case "IPv6":
        address = "2001:db8::129"
        srcAddress = srcAddrV6
}

cV := new(oc.Sampling_Sflow_Collector)
cV.SetAddress(address)
cV.SetPort(6343)

if deviations.SflowSourceAddressUpdateUnsupported(d) {
sFlowSourceAddressCli := ""
switch d.Vendor() {
case ondatra.ARISTA:
	sFlowSourceAddressCli = fmt.Sprintf("sflow vrf %s source-interface %s", ni, intf.GetName())
}
if sFlowSourceAddressCli != "" {
	helpers.GnmiCLIConfig(t, d, sFlowSourceAddressCli)
}
} else {
cV.SetSourceAddress(srcAddress)
}
cV.SetNetworkInstance(ni)
coll = append(coll, cV)
```

2025-01-03 04:46 UTC, rohit-rp submitted a review, later dismissed

2025-01-03 17:00 UTC, trathod1 commented on internal/cfgplugins/sflow.go
> +		switch ip {
Sounds good. Committed these changes.

2025-01-06 04:17 UTC, nsadhasivam requested changes

2025-01-06 04:17 UTC, nsadhasivam commented on feature/sflow/otg_tests/sflow_base_test/sflow_base_test.go
> +	if !found || sampleCount < 8 {
Can you please have a variable tolerance = 1 expectedSampleCount = 9 
And change the condition to sampleCount <= (expectedSampleCount - tolerance)

2025-01-06 16:45 UTC, trathod1 commented on feature/sflow/otg_tests/sflow_base_test/sflow_base_test.go
> +	if !found || sampleCount < 8 {
Updated script to use the existing `sampleTolerance`.

2025-01-07 04:49 UTC, nsadhasivam approved these changes
LGTM!

2025-01-07 05:04 UTC, self-maurya approved these changes

2025-01-07 05:18 UTC, merged