Daveruturaj patch 2
openconfig/featureprofiles pull request #3493
Opened 2024-10-02 19:55 UTC by daveruturaj

Creating a pull request to write tests for MPLSoGUE.

2024-10-03 01:45 UTC, robshakir requested changes

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +
Please line wrap to 80ch.

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +This is to test the the functionality of policy-based forwarding (PF) to decapsulate Generic UDP Encapsulation (GUE) traffic. These tests verify the use case of MPLSoGUE to IPv4 GUE tuennel. The test
```suggestion
This is to test the the functionality of policy-based forwarding (PF) to decapsulate Generic UDP Encapsulation (GUE) traffic. These tests verify the use case of MPLSoGUE to IPv4 GUE tunnel. The tests are meant for `Tunnel Interface` or `Policy Based` implementation of IPv4 GUE tunnel. The tests validate that the DUT performs the following action.
```

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +This is to test the the functionality of policy-based forwarding (PF) to decapsulate Generic UDP Encapsulation (GUE) traffic. These tests verify the use case of MPLSoGUE to IPv4 GUE tuennel. The test
Per comments elsewhere, I'm not sure that I understand why we have these variants -- this seems like a deviation for the same functionality.

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> + - DUT is a transient node to forward MPLSoGUE traffic.
Transit node?

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +*  ATE Port 1: Generates GUE-encapsulated traffic with various inner (original) destinations.
Please expand on the specification of "various" -- what is the expected number of 5-tuples and what fields do they vary in?

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +    *  Configure an IPv4 static route to GUE decapsulation destination (DECAP-DST) to Null0.
`Null0` seems vendor specific -- can we specify that this is a route that blackholes traffic?

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +       *  If udp port is not configured then the default GUE UDP port will be inherited/used.
Is the expectation that even for MPLSoGUE the destination port is set to 6080? Can we explicitly specify the value here?

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +    *  Apply the defined policy on the Ingress (DUT port1) port.
What is the defined policy? Is it the policy-forwarding policy defined below?

Please add a clarification.

2024-10-03 01:45 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +## Config Parameter Coverage
Please add TODOs for these sections.

2025-03-26 19:00 UTC, daveruturaj commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> + - DUT is a transient node to forward MPLSoGUE traffic.
Yes, this is a use case of IP+UDP+IP+UDP+MPLS+<Payload>.

2025-03-26 22:13 UTC, daveruturaj commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +    *  Configure an IPv4 static route to GUE decapsulation destination (DECAP-DST) to Null0.
done

2025-03-26 22:14 UTC, daveruturaj commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +## Config Parameter Coverage
done

2025-03-26 22:16 UTC, daveruturaj commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +       *  If udp port is not configured then the default GUE UDP port will be inherited/used.
this is IPGUE+MPLSoGUE

2025-06-13 21:44 UTC, robshakir commented on feature/policy_forwarding/GUE/Outer_IPv4/decapsulation/otg_tests/Inner_MPLS/README.md
> +
Can we add canonical OpenConfig here please?

2025-08-09 00:33 UTC, closed without merging

2025-08-09 00:33 UTC, sachendras commented
The feature is not needed anymore