Extend coverage to verify "INVERT" match option for prefix-set
openconfig/featureprofiles pull request #3501
Opened 2024-10-07 20:48 UTC by rszarecki

2024-10-08 00:46 UTC, dplore requested changes
Thanks for this @rszarecki ,  couple of comments for you.

2024-10-08 00:46 UTC, dplore commented on feature/bgp/policybase/otg_tests/prefix_set_test/README.md
>  ## Config Parameter Coverage
Note, you should delete this heading and the `## Telemetry Parameter coverage` heading.  They are  redundant to the `## OpenConfig Path and RPC Coverage` heading.

2024-10-08 00:46 UTC, dplore commented on feature/bgp/policybase/otg_tests/prefix_set_test/README.md
> +  *	DUT conditionally advertises prefixes received from ATE port-1 to ATE port-2 after policy application. Ensure that multiple routes are accepted and advertised to the neighbor on ATE port-2.
Please also specify exactly which prefix-sets are expected to be received on ATE port-2.

(the way I read it, is only routes from prefix-set-3 should be received on ATE port-2.)

2024-10-08 00:46 UTC, dplore commented on feature/bgp/policybase/otg_tests/prefix_set_test/README.md
> +* For IPv4 and IPv6:
Is the intent is to keep the configuration which was applied in RT-1.33.1 and add the following config?

If yes, can you add a specification that says use `gnmi.Set` with `replace` option and includes the config from RT-1.33.1 and RT-1.33.2.  Good language to use which will help a developer is:

Generate configuration <blah, blah, blah>
Push the generated configuration to the DUT using gnmi.Set with replace option.

2024-10-08 00:46 UTC, dplore commented on feature/bgp/policybase/otg_tests/prefix_set_test/README.md
> +* For IPv4 and IPv6:
Please provide canonical OC (in JSON format) for each section.

2024-10-15 20:37 UTC, dplore reviewed
For the TODO, please add a github issue tracking the implementation of the TODO items

2025-05-08 05:44 UTC, ram-mac approved these changes
LGTM

2025-05-08 06:38 UTC, merged