RT-1.29: BGP chained import/export policy attachment changes incorpor…
openconfig/featureprofiles pull request #3505
Opened 2024-10-09 20:24 UTC by ampattan

Updated metadata.textproto

 vender check included for NOKIA
 Added deviations.

Updated chained_policies_test.go

 Removed accept route for statement match-policy-v4 & match-statement-v6 as the next statement prefix-set-v4 & prefix-set-v6 will not be applied if accept route is configured.
 Refer PR- #2760

 Added deviations for prefixset_Mode.

 Updated to use batch replace for delete routing-policies.

Updated README.md

 policy-result as `ACCEPT_ROUTE` not required for match-policy-v4 & match-statement-v6 policy.
 Refer PR- #2760

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

2024-11-15 23:04 UTC, dplore commented
/fptest virtual

2024-11-16 00:04 UTC, dplore commented
@ampattan , not this does not pass on srlinux container.  see logs from https://github.com/openconfig/featureprofiles/pull/3505#issuecomment-2403364930

2024-11-20 01:20 UTC, trathod1 commented
/fptest virtual

2024-11-21 01:53 UTC, dplore commented
/fptest virtual

2024-11-22 01:25 UTC, dplore commented
This fails on srlinux.  See logs:  https://gist.github.com/dplore/9ea5bafc71eb026ef8b8925e08f458fc

Please fix and on next submission, include logs showing pass results on your platform

2024-11-22 03:31 UTC, trathod1 commented
HW log with these changes are avaialbe at - b/380289415.

> This fails on srlinux. See logs: https://gist.github.com/dplore/9ea5bafc71eb026ef8b8925e08f458fc

This log is with older image.  Latest image would work fine for these failures. However, considering this is a KNE run, there is an open issue which is getting tracked here - https://github.com/open-traffic-generator/fp-testbed-nokia/issues/30

2025-01-30 16:48 UTC, nsadhasivam submitted a review, later dismissed
Please share the pass logs for the PR

2025-01-30 16:48 UTC, nsadhasivam commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +		stmt2.GetOrCreateActions().GetOrCreateBgpActions().SetMedAction = oc.BgpPolicy_BgpSetMedAction_SET
undefined: oc.BgpPolicy_BgpSetMedAction_SET

2025-02-05 07:32 UTC, ampattan commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +		stmt2.GetOrCreateActions().GetOrCreateBgpActions().SetMedAction = oc.BgpPolicy_BgpSetMedAction_SET
The new YANG implementation for setting, incrementing, and decrementing MED values is available from `ondatra-0.7.0` onwards. Please refer to `PR-3739`.

2025-02-05 07:33 UTC, ampattan commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +		stmt2.GetOrCreateActions().GetOrCreateBgpActions().SetMedAction = oc.BgpPolicy_BgpSetMedAction_SET
The new YANG implementation for setting, incrementing, and decrementing MED values is available from ondatra-0.7.0 onwards. Please refer to PR-3739.

2025-02-27 06:59 UTC, nsadhasivam commented
/fptest physical

2025-02-27 07:00 UTC, nsadhasivam commented
/fptest virtual

2025-03-17 10:38 UTC, ksgireesha commented
@nsadhasivam , review this please

2025-03-22 03:13 UTC, ram-mac commented
@ampattan - The validation fails for Nokia. Have shared the logs in the Chat space for reference.

2025-03-22 03:17 UTC, ram-mac requested changes
Address the comments and also reassigning PR back to Nokia as validation is failing.

2025-03-22 03:17 UTC, ram-mac commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +	time.Sleep(3 * time.Second)
Please remove this static sleep in the code. Use gnmi.Await or gnmi.Watch function

2025-03-24 06:18 UTC, nsadhasivam commented
Image that is shared does not support oc.BgpPolicy_BgpSetMedAction_SET, to verify on 69530 onwards once available

2025-04-02 02:33 UTC, rszarecki requested changes

2025-04-02 02:33 UTC, rszarecki commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +		stmt2.GetOrCreateActions().GetOrCreateBgpActions().SetMedAction = oc.BgpPolicy_BgpSetMedAction_SET
This change will break any implementation that follow OpenConfig older then 08/2024.

Please refactor test code such older implementation are supported w/o deviation, and use of `set-med-action' is gated by deviation. Or vice-a-versa.

2025-04-02 22:00 UTC, MarcCharlebois commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +		stmt2.GetOrCreateActions().GetOrCreateBgpActions().SetMedAction = oc.BgpPolicy_BgpSetMedAction_SET
>Please refactor test code such older implementation are supported w/o deviation, and use of `set-med-action' is gated by deviation. Or vice-a-versa.


I don't entirely think that writing a deviation for a supported operation is OC (either way) should be a way forward here. Can we simply add a switch case for vendors instead of writing a deviation for something that's supported?

Once the last vendor migrates to using this path, they can remove the switch case and add it as baseline code?

2025-04-11 13:10 UTC, ampattan commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +		stmt2.GetOrCreateActions().GetOrCreateBgpActions().SetMedAction = oc.BgpPolicy_BgpSetMedAction_SET
`BgpSetMedActionUnsupported `deviation has been introduced to accommodate `set-med `action changes.

2025-04-23 15:05 UTC, ampattan commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +		stmt2.GetOrCreateActions().GetOrCreateBgpActions().SetMedAction = oc.BgpPolicy_BgpSetMedAction_SET
@ram-mac @rszarecki Since the `set-med` action changes were already incorporated in PR #4133 by @AmrNJ, do we still need the deviation?

2025-04-28 19:03 UTC, ampattan commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +	time.Sleep(3 * time.Second)
removed the sleep

2025-04-29 21:12 UTC, rszarecki submitted a review, later dismissed

2025-05-05 08:26 UTC, ram-mac requested changes
@ampattan - Please make changes regarding teh deviations mentioned in the comments and assign back to me for validation.

2025-05-05 12:21 UTC, ampattan commented on feature/bgp/policybase/otg_tests/chained_policies_test/chained_policies_test.go
> +		stmt2.GetOrCreateActions().GetOrCreateBgpActions().SetMedAction = oc.BgpPolicy_BgpSetMedAction_SET
@ram-mac `set-med` action deviation removed.

2025-05-05 15:17 UTC, ampattan commented
> @ampattan - Please make changes regarding teh deviations mentioned in the comments and assign back to me for validation.

Addressed.

2025-05-06 06:33 UTC, ram-mac requested changes

2025-05-06 06:33 UTC, ram-mac commented on proto/metadata_go_proto/metadata.pb.go
> +// 	protoc-gen-go v1.36.5
@ampattan - Since deviations are removed, we do not need changes in this file. Request you to take these changes out from this PR

2025-05-06 06:40 UTC, ampattan commented on proto/metadata_go_proto/metadata.pb.go
> +// 	protoc-gen-go v1.36.5
Remove `metadata.pb.go` file

2025-05-07 08:38 UTC, rohit-rp approved these changes

2025-05-07 08:45 UTC, merged