RT-2.12 Fixed with deviations & minor changes
openconfig/featureprofiles pull request #3513
Opened 2024-10-11 17:05 UTC by snaragund

- Defined new Nokia deviation 'EnableTableConnections' & updated metadata.proto, metadata.pb.go & deviations.go.
- Added deviations required.
- Edited dp2v6Route such that it is advertised as ISIS route.
- Set separate tag value for IPv4 & IPv6 as per README.
- Added missing 'metricPropogation' parameter in 2.12.8 case.

PS: Script needs alteration (apart from this PR) such that it adheres to README.

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

2024-11-16 00:08 UTC, dplore commented
/fptest virtual

2024-11-16 00:15 UTC, dplore requested changes
minor nit comments

2024-11-16 00:15 UTC, dplore commented on feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
> +		t.Fatalf("Unsupported vendor %s for deviation 'UseVendorNativeACLConfiguration'", d.Vendor())
```suggestion
		t.Fatalf("Unsupported vendor %s for deviation 'EnableTableConnections'", d.Vendor())
```

2024-11-16 00:15 UTC, dplore commented on feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
> +	t.Log("Recieved parameters of table connections")
```suggestion
	t.Log("Received parameters of table connections")
```

2024-11-16 00:16 UTC, dplore commented
Please also check that [fptest virtual](https://github.com/openconfig/featureprofiles/pull/3513#issuecomment-2407811147) test passes on your platform as expected

2024-11-16 15:27 UTC, snaragund commented on feature/isis/otg_tests/static_route_isis_redistribution/static_route_isis_redistribution_test.go
> +		t.Fatalf("Unsupported vendor %s for deviation 'UseVendorNativeACLConfiguration'", d.Vendor())
Updated as per comments.

2024-11-17 18:35 UTC, snaragund commented
/fptest nokia-srl

2024-11-18 15:11 UTC, dplore commented
/fptest virtual

2024-11-22 10:34 UTC, snaragund commented
Shared hardware logs through https://partnerissuetracker.corp.google.com/issues/380289415 please do check.

2024-12-03 03:40 UTC, dplore approved these changes

2024-12-03 03:40 UTC, merged