[gNMI-1.10] add InterfaceCountersUpdateDelayed deviation
openconfig/featureprofiles pull request #3536
Opened 2024-10-22 20:05 UTC by kjahed

1- Add InterfaceCountersUpdateDelayed deviation for CISCO (see PR #2805)
2- Use lookup instead of get for component type. Some of the parent component may not map to any of identity types defined under OPENCONFIG_HARDWARE_COMPONENT, for those components type leaf would not be returned (see PR #2808).

2024-10-24 16:55 UTC, dplore requested changes
Thanks for this.  Your new function is better than the existing.  Our intent is to test using gnmi.Subscribe with SAMPLE mode.  I suggest you replace  the existing `fetchInAndOutPkts` with your new function.

2024-12-03 03:46 UTC, dplore commented
/fptest virtual

2025-01-22 06:40 UTC, ram-mac commented
@kjahed - Can you please take care of the comments requested by Darren?

2025-01-23 19:41 UTC, kjahed commented
> @kjahed - Can you please take care of the comments requested by Darren?

@ram-mac  done.

2025-01-28 19:10 UTC, dplore commented
/fptest virtual

2025-01-28 19:58 UTC, dplore approved these changes
Ran this in our environment and it is passing as expected, thanks.

2025-01-29 02:37 UTC, ram-mac approved these changes
LGTM

2025-01-29 02:38 UTC, merged