Moved the capturePktsBeforeTraffic & added deviation for isisLevelEnabled.
openconfig/featureprofiles pull request #3550
Opened 2024-10-29 16:30 UTC by priyaranjannanda

Changes for  

- Adding deviation isisLevelEnabled. for Juniper 
- Moved capturePktsBeforeTraffic before interfaces are down.

2024-11-21 11:14 UTC, ram-mac commented
Hello,
 Please address following comments
 1) The static analysis is failing
 2) The traffic distribution weights are change to 50/50 was 33/67 earlier. What is the reason for change?
 3) The frame size is changed to 1400 from 1500; was wondering if the test fails with 1500 frame size?

2024-11-21 12:19 UTC, ram-mac commented
Hi,
 I fixed the ln1206 where it is failing "rxs = append(rxs, inFrames)" which originally is "rxs = append(rxs, inOctets)"
 However, after this fix also the test fails. Please let me know if it is passing at ur end.

2024-11-28 09:08 UTC, priyaranjannanda commented
> Hi, I fixed the ln1206 where it is failing "rxs = append(rxs, inFrames)" which originally is "rxs = append(rxs, inOctets)" However, after this fix also the test fails. Please let me know if it is passing at ur end.

Hi,

I have changed it to inFrames and it is passing now.

--
Priya Ranjan

2024-11-28 09:19 UTC, priyaranjannanda commented
> Hello, Please address following comments
> 
> 1. The static analysis is failing
> 2. The traffic distribution weights are change to 50/50 was 33/67 earlier. What is the reason for change?
> 3. The frame size is changed to 1400 from 1500; was wondering if the test fails with 1500 frame size?

Hi,

1. I have uploaded new changes and  static analysis has passed.

2 & 3 . 
There are 2 traffic profiles (pfx1ToPfx2_3, pfx1ToPfx4) transmitting traffic to lag2 and one profile (pfx1ToPfx2_3 ) transmitting traffic to lag3.

Load balance percent per readme is 50/50 , but testcase is coded with 33/67 for lag2/lag3 respectively.
When weight (load balance) is calculated for pfx1ToPfx2_3, entire traffic to lag2 and lag3 are considered.
Traffic is sent with fixed packet size of 1500 bytes and default interface mtu is 1514. gRIBI route is programmed to encap traffic as IPinIP which leads to fragmentation of packet in the egress lag2 interface.

While calculating the balance, subtracted the traffic received for profile pfx1ToPfx4 in lag2 and calculated the weight using rest of the traffic in lag2.


https://github.com/openconfig/featureprofiles/blob/main/feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/README.md#rt-5721-make-the-forwarding-viable-transitions-from-true----false-on-ports-3-6-within-the-lag_2-on-the-dut

2024-12-26 04:10 UTC, ram-mac commented
hi,
Can we fix the conflicts; I think some other changes has gone into aggregate_all_not_forwarding_viable_test.go test

2025-01-02 05:11 UTC, priyaranjannanda commented
> hi, Can we fix the conflicts; I think some other changes has gone into aggregate_all_not_forwarding_viable_test.go test

Hi Ram,

I have resolved the conflict. Please re-review.

--
Thanks & Regards,
Priya Ranjan

2025-01-02 11:03 UTC, ram-mac commented
> > hi, Can we fix the conflicts; I think some other changes has gone into aggregate_all_not_forwarding_viable_test.go test
> 
> Hi Ram,
> 
> I have resolved the conflict. Please re-review.
> 
> -- Thanks & Regards, Priya Ranjan

Hi Priya,
 The static analysis is failing. It looks to be some formatting issue. Please fix it
-Ram

2025-01-02 11:53 UTC, priyaranjannanda commented
> > > hi, Can we fix the conflicts; I think some other changes has gone into aggregate_all_not_forwarding_viable_test.go test
> > 
> > 
> > Hi Ram,
> > I have resolved the conflict. Please re-review.
> > -- Thanks & Regards, Priya Ranjan
> 
> Hi Priya, The static analysis is failing. It looks to be some formatting issue. Please fix it -Ram

Hi Ram,

I have fixed the formatting issue and static check has passed. Please review.

--
Thanks & Regards,
Priya Ranjan

2025-01-02 14:21 UTC, ram-mac commented
Looks Good now.

2025-01-02 14:22 UTC, ram-mac approved these changes
LGTM

2025-01-03 04:49 UTC, rohit-rp approved these changes

2025-01-03 04:54 UTC, merged

2025-01-03 04:55 UTC, self-maurya requested changes

2025-01-03 04:55 UTC, self-maurya commented on feature/interface/aggregate/otg_tests/aggregate_all_not_viable_test/aggregate_all_not_forwarding_viable_test.go
> +		if dut.Vendor() != ondatra.CISCO && dut.Vendor() != ondatra.JUNIPER {
Vendor based should not be used unless wrapper under deviation.

Please use deviation based on this reference https://github.com/openconfig/featureprofiles/blob/main/internal/deviations/README.md#when-to-use-deviations
or if the feature is not supported then we can keep it failing.