GNMI-1.18: Skipping check for empty integrated-circuit and removing deviations
openconfig/featureprofiles pull request #3560
Opened 2024-11-05 21:03 UTC by trathod1

Following changes are made here - 
   1. Removing all deviations for Nokia
   2. Skipping checks for empty `integrated-circuit`

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

2024-12-02 12:19 UTC, nsadhasivam requested changes

2024-12-05 17:26 UTC, trathod1 commented on feature/platform/fabric/otg_tests/sampled_backplane_capacity_counters_test/sampled_backplane_capacity_counters_test.go
> -		if gnmi.Get(t, dut, gnmi.OC().Component(f).Removable().State()) {
I have restored the check if the active component is removable.

2024-12-26 12:18 UTC, nsadhasivam approved these changes
LGTM!

2024-12-26 12:21 UTC, self-maurya approved these changes

2024-12-26 12:22 UTC, merged