BGP internal/external distance deviation
openconfig/featureprofiles pull request #3564
Opened 2024-11-06 19:21 UTC by manan-patel

2024-11-07 20:15 UTC, dplore requested changes

2024-11-07 20:15 UTC, dplore commented
/fptest virtual

2024-11-08 04:07 UTC, manan-patel commented on feature/bgp/admin_distance/otg_tests/admin_distance_test/admin_distance_test.go
> +							TextWithGNMI(context.Background(), t, ts.DUT, fmt.Sprintf(`
Comment addressed

2024-11-08 04:43 UTC, dplore commented
/fptest virtual

2024-11-08 04:44 UTC, dplore commented
/fptest cisco-8808

2024-12-03 03:45 UTC, dplore commented
Hi @manan-patel there are still conflicts

2025-04-08 17:09 UTC, dplore commented
/fptest virtual

2025-04-09 04:18 UTC, ram-mac commented
@manan-patel @arvbaska1 
Problem is that this deviations is using a CLI and it is not acceptable now. Is there another way to fix this? Can we explore a native OC path support for this one until we get support on this feature?

2025-05-06 03:15 UTC, ram-mac commented
> @manan-patel @arvbaska1 Problem is that this deviations is using a CLI and it is not acceptable now. Is there another way to fix this? Can we explore a native OC path support for this one until we get support on this feature?

Hello @manan-patel @arvbaska1 - Based on the discussion internally, now we are accepting the CLI as an alternate via deviation. But make sure we have a tracking bug raised for the deviation.

2025-05-06 03:15 UTC, ram-mac commented
@manan-patel @arvbaska1 - Can you please resolve the conflicts, so i can validate the PR and close on it.

2025-05-08 06:08 UTC, ram-mac approved these changes
Changes look good. Validated on Cisco and it is passing now.

2025-05-08 06:09 UTC, rohit-rp approved these changes

2025-05-08 06:10 UTC, merged