RT-7.2: BGP Policy Community Set changes incorporated
openconfig/featureprofiles pull request #3592
Opened 2024-11-14 17:54 UTC by ampattan

Updated metadata.textproto
 - Removed "bgp_conditions_match_community_set_unsupported" deviation.

Updated community_test.go

 - Added deviation check "bgp_conditions_match_community_set_unsupported" for "match-set-options" configuration under the "defined-sets".

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

2024-11-25 18:19 UTC, trathod1 commented
HW log with these changes are available at - b/380835423

2025-03-17 10:36 UTC, ksgireesha commented
@rohit-rp , can you review this please

2025-04-07 04:39 UTC, rohit-rp requested changes

2025-04-07 04:39 UTC, rohit-rp commented on feature/bgp/policybase/otg_tests/community_test/community_test.go
> +			communitySet.SetMatchSetOptions(matchSetOptions)
```suggestion
		if !deviations.BGPConditionsMatchCommunitySetUnsupported(dut) {
			communitySet.SetMatchSetOptions(matchSetOptions)
```

2025-04-07 04:39 UTC, rohit-rp commented on feature/bgp/policybase/otg_tests/community_test/metadata.textproto
>    }
```suggestion
    bgp_conditions_match_community_set_unsupported: true
  }
```

2025-04-07 15:10 UTC, trathod1 commented on feature/bgp/policybase/otg_tests/community_test/community_test.go
> +			communitySet.SetMatchSetOptions(matchSetOptions)
We discussed this behavior here also - https://github.com/openconfig/featureprofiles/pull/3574#discussion_r1854438768 

The deviation `BGPConditionsMatchCommunitySetUnsupported` is meant for `match-set-option` under `bgp-condition`, thus, if it is not supported than only the older way of using `match-set-option` under `bgp-defined-set` will be used.

2025-04-29 16:19 UTC, rohit-rp approved these changes, later dismissed

2025-04-29 18:42 UTC, trathod1 commented on feature/bgp/policybase/otg_tests/community_test/community_test.go
> +			time.Sleep(3 * time.Second)
Removed sleep with `WaitForARP`.

2025-04-30 00:50 UTC, nikki-blr approved these changes

2025-04-30 01:00 UTC, nikki-blr commented
Can we get this rebased to merge please ?

2025-04-30 03:09 UTC, merged