RT-7.5 Fixed timing of policy application & peergroup configurations
openconfig/featureprofiles pull request #3611
Opened 2024-11-27 15:56 UTC by snaragund

- Added delays for policy & v6 OTG config to take effect.
  - Added peerGroup at bgp for v4 & v6.
  - Cosmetic changes in logs.

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

2024-11-27 17:55 UTC, dplore commented
Please provide logs of this test run (can be provided by internal google bug or publicly using gist.github.com)

2024-11-27 17:55 UTC, dplore commented
/fptest virtual

2024-11-27 18:12 UTC, snaragund commented
> Please provide logs of this test run (can be provided by internal google bug or publicly using gist.github.com)

Attached Hw logs in https://partnerissuetracker.corp.google.com/issues/381220602

2024-12-13 18:37 UTC, dplore commented
/fptest virtual

2024-12-27 20:12 UTC, dplore commented
/fptest virtual

2025-01-30 20:41 UTC, dplore requested changes

2025-01-30 20:41 UTC, dplore commented on feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
> +			time.Sleep(20 * time.Second)
instead of adding sleep here, use gnmi.Watch with .Await in the appropriate validate function calls.  

For reference, see the ONDATRA best practice on avoiding use of sleep in tests. 
 https://pkg.go.dev/github.com/openconfig/ondatra/gnmi#hdr-Best_Practice__Avoid_time_Sleep

2025-03-17 09:53 UTC, ksgireesha commented
@dplore , Please address these changes.

2025-03-17 11:37 UTC, snaragund commented on feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
> +	time.Sleep(5 * time.Second)
@dpore have fixed this using gnmi.Watch. Thank you

2025-03-18 17:46 UTC, snaragund commented
> @snaragund , Please address these changes.

@ksgireesha  Addressed.

2025-03-18 17:46 UTC, snaragund commented on feature/bgp/policybase/otg_tests/link_bandwidth_test/link_bandwidth_test.go
> +			time.Sleep(20 * time.Second)
@dplore have fixed this. Please take a look.

2025-03-20 21:47 UTC, dplore reviewed
This LGTM, please share logs showing test results

2025-03-21 17:30 UTC, dplore approved these changes

2025-03-21 17:59 UTC, merged