RT-7.3: Fixing IPv6 route generation, DefaultImportPolicy and regexp pattern
openconfig/featureprofiles pull request #3632
Opened 2024-12-11 03:18 UTC by trathod1

Following changes are made here -
  1. Fixing IPv6 route generation to have AsPath set as expected by Readme test and as it was done for IPv4.
  2. Fixing DefaultImportPolicy for IPv4 to "Reject" as required by eBGP, and as it was before PR-3025
  3. Removing `^` from the regexp `aspathMatch` from the beginning, considering these eBGP routes will always AsPath with neighbor AS `65511` at the start, and will never match `^100`

"This code is a Contribution to the OpenConfig Feature Profiles project ("Work") made under the Google Software Grant and Corporate Contributor License Agreement ("CLA") and governed by the Apache License 2.0. No other rights or licenses in or to any of Nokia's intellectual property are granted for any other purpose. This code is provided on an "as is" basis without any warranties of any kind."

2024-12-12 16:37 UTC, trathod1 commented
HW log with these changes are available at - b/383732784

2025-03-04 10:28 UTC, ram-mac reviewed
The test is not passing for Nokia. It is not accepting the as-path-sets and fails to push the configuration.

Replace(t) on dut(xxxxxx) at /routing-policy: Replace(t) at path origin:"openconfig" elem:{name:"routing-policy"}: rpc error: code = NotFound desc = error on request {
        prefix: {
          target: "xxxxxx"
        }
        replace: {
          path: {
            origin: "openconfig"
            elem: {
              name: "routing-policy"
            }
          }
          val: {
            json_ietf_val: "{\n  \"openconfig-routing-policy:defined-sets\": {\n    \"openconfig-bgp-policy:bgp-defined-sets\": {\n      \"as-path-sets\": {\n        \"as-path-set\": [\n          {\n            \"as-path-set-name\": \"match_my_regex_aspath-1\",\n            \"config\": {\n              \"as-path-set-member\": [\n                \"100\",\n                \"20[0-9]\",\n                \"200$\"\n              ],\n              \"as-path-set-name\": \"match_my_regex_aspath-1\"\n            }\n          }\n        ]\n      }\n    }\n  },\n  \"openconfig-routing-policy:policy-definitions\": {\n    \"policy-definition\": [\n      {\n        \"config\": {\n          \"name\": \"PERMIT-ALL\"\n        },\n        \"name\": \"PERMIT-ALL\",\n        \"statements\": {\n          \"statement\": [\n            {\n              \"actions\": {\n                \"config\": {\n                  \"policy-result\": \"ACCEPT_ROUTE\"\n                }\n              },\n              \"config\": {\n                \"name\": \"id-1\"\n              },\n              \"name\": \"id-1\"\n            }\n          ]\n        }\n      },\n      {\n        \"config\": {\n          \"name\": \"routePolicy\"\n        },\n        \"name\": \"routePolicy\",\n        \"statements\": {\n          \"statement\": [\n            {\n              \"actions\": {\n                \"config\": {\n                  \"policy-result\": \"ACCEPT_ROUTE\"\n                }\n              },\n              \"conditions\": {\n                \"openconfig-bgp-policy:bgp-conditions\": {\n                  \"match-as-path-set\": {\n                    \"config\": {\n                      \"as-path-set\": \"match_my_regex_aspath-1\",\n                      \"match-set-options\": \"ANY\"\n                    }\n                  }\n                }\n              },\n              \"config\": {\n                \"name\": \"routePolicyStatement\"\n              },\n              \"name\": \"routePolicyStatement\"\n            }\n          ]\n        }\n      }\n    ]\n  }\n}"
          }
        }
        }: Schema '/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/match-as-path-set/config' has no local leaf with the name 'match-set-options'. Options are [as-path-set]: Parse error on line 61:                       "as-path-set": "match_my_regex_aspath-1...
        Input:
        '{
          "openconfig-routing-policy:defined-sets": {
            "openconfig-bgp-policy:bgp-defined-sets": {
              "as-path-sets": {
                "as-path-set": [
                  {
                    "as-path-set-name": "match_my_regex_aspath-1",
                    "config": {
                      "as-path-set-member": [
                        "100",
                        "20[0-9]",
                        "200$"
                      ],
                      "as-path-set-name": "match_my_regex_aspath-1"
                    }
                  }
                ]
              }
            }
          },

2025-03-04 10:28 UTC, ram-mac commented on feature/bgp/policybase/otg_tests/aspath_test/aspath_test.go
> +			aspathMatch:     []string{"100", "20[0-9]", "200$"},
@trathod1 - It should work even without this change. what is the need to change this regex?

2025-03-04 10:41 UTC, ram-mac requested changes

2025-03-04 10:41 UTC, ram-mac commented on feature/bgp/policybase/otg_tests/aspath_test/metadata.textproto
> +    interface_enabled: true
@trathod1  -  These deviations are not used in this test AFAIK, so why add these? Can you tell me what is the need for these deviations?

2025-03-04 16:41 UTC, trathod1 commented on feature/bgp/policybase/otg_tests/aspath_test/aspath_test.go
> +			aspathMatch:     []string{"100", "20[0-9]", "200$"},
I tried to cover the reasoning in the description above - 
     3.  Removing `^` from the regexp aspathMatch at the start, considering these eBGP routes will always have AsPath with neighbor AS `65511` at the start, and will never match `^100`

2025-03-04 16:41 UTC, trathod1 commented on feature/bgp/policybase/otg_tests/aspath_test/metadata.textproto
> +    interface_enabled: true
This test calls `cfgplugins.NewBGPSession` -
https://github.com/nokia/featureprofiles/blob/7de4e45e964d7c5498476d4acaea71e144eaf35c/feature/bgp/policybase/otg_tests/aspath_test/aspath_test.go#L221

Which calls `configOCInterface` at line 179 -
https://github.com/nokia/featureprofiles/blob/21a3203408f28a4ac635d178c330c0dec71fd893/internal/cfgplugins/bgp.go#L179

This deviation is used at line 83 and 97 there - 
    https://github.com/nokia/featureprofiles/blob/main/internal/attrs/attrs.go#L83
    https://github.com/nokia/featureprofiles/blob/main/internal/attrs/attrs.go#L97

2025-03-04 16:41 UTC, trathod1 commented
> @trathod1 - Do you have a pass log for this test?

Pass log is available at - https://github.com/openconfig/featureprofiles/pull/3632#issuecomment-2539455257

2025-03-04 17:01 UTC, ram-mac commented
Have Attached the failed logs in b/383732784, take a look.

2025-03-04 17:29 UTC, trathod1 commented
> Have Attached the failed logs in b/383732784, take a look.

Failed log shows incorrect image. Updated b/383732784 with details.

2025-03-05 07:28 UTC, ram-mac commented
The test is passing for Nokia using the recommended image.
However the test is failing for all the other vendors. So we can let that happen.

2025-03-17 10:12 UTC, ksgireesha commented
@ram-mac , can you address these changes please

2025-03-21 13:41 UTC, ram-mac approved these changes
Validated the new changes and the test is now passing.
Hence approving the PR

2025-03-21 15:05 UTC, rohit-rp approved these changes

2025-03-21 15:05 UTC, merged