adding breakout config code
openconfig/featureprofiles pull request #3648
Opened 2024-12-16 00:28 UTC by mastarkey

Test is for breakout config for the following modes

4x100
2x100
4x10

2024-12-18 00:38 UTC, dplore commented
/gcbrun

2024-12-18 06:10 UTC, dplore commented
/fptest cisco-8808

2024-12-18 21:10 UTC, amrindrr submitted a review, later dismissed
Please fix static analysis errors before submitting

2024-12-18 23:35 UTC, amrindrr approved these changes

2024-12-19 20:18 UTC, amrindrr commented on feature/platform/tests/breakout_configuration/breakout_base_test.go
Ideally there should be singe _test.go file in a folder. I see this file has most of helper functions and doesn't include any Test function. I would suggest to move the helper functions inside /internal. For example functions related to platform probably could go into a library that's already started at: internal/components/components.go. Similarly different location for IP address incrementing function (inside /internal)

2024-12-19 20:48 UTC, mastarkey commented on feature/platform/tests/breakout_configuration/breakout_base_test.go
can we merge this I will raise a git issue to make those changes. This item has been here for almost a year and there is endless back and forth on this. At a minimum i would like to merge it just to stop having to make changes to the devations.go file which are constantly eating my time to resolve it only for someone to make some other suggestions on the case. so ideally can we merge this and raise an git issue on those changes

2024-12-19 20:51 UTC, mastarkey commented
Hi @dplore can you looking into approving this its waiting on your approval.

2024-12-19 21:40 UTC, amrindrr commented on feature/platform/tests/breakout_configuration/breakout_base_test.go
Sounds good. You can send separate PR to make file and helper function changes.

2024-12-19 21:44 UTC, dplore commented on feature/platform/tests/breakout_configuration/breakout_base_test.go
Yes, making refactoring the helpers can be in a follow up PR.  
issue tracking: https://github.com/openconfig/featureprofiles/issues/3663

2024-12-19 21:45 UTC, dplore commented
/fptest cisco-8808

2024-12-19 21:47 UTC, amrindrr commented
/fptest

2024-12-20 01:51 UTC, dplore requested changes
@mastarkey hi, this is ready to merge given the follow up issue, except there are still 7 static checks failing.  Can you please resole those and I'll approve and merge.

@amrindrr will iterate with you regarding the CLI used for determining breakout capability since there are not currently any OC paths for querying breakout capabilities

2024-12-20 02:02 UTC, dplore commented on feature/platform/tests/breakout_configuration/breakout_test.go
> +				// other vendor method
to fix the "block is empty" comment, you can add something like:

		t.Fatalf("Unsupported vendor %s.  Need to add breakout component names.", d.Vendor())

2024-12-20 21:29 UTC, amrindrr submitted a review, later dismissed

2024-12-20 23:25 UTC, dplore approved these changes

2024-12-20 23:27 UTC, dplore submitted a review, later dismissed
This looks good, except there are still several style/static analysis issues. Can you please resolve?

You can view them all here:
https://github.com/openconfig/featureprofiles/pull/3648/files

2025-01-13 17:22 UTC, dplore commented
/fptest physical

2025-01-13 17:26 UTC, dplore submitted a review, later dismissed
Code structure looks good to me, noting outstanding issue at https://github.com/openconfig/featureprofiles/issues/3663

@amrindrr to confirm this is passing on at least Cisco hardware in our lab environment

2025-03-05 09:31 UTC, AmrNJ commented on feature/platform/tests/breakout_configuration/breakout_test.go
> +			portPrefix:    "HundredGigE",
1. Assuming 4 x 100g is already configured, is it possible to start the test on a 4 x 100g and then proceed to check for the other breakouts - 2 x 100g and 4 x 10g? 
2. Only 4 ports needed for the test to run. All breakouts can be checked with this. 
3. All Cisco specific code to be moved under switch case. 

-  port prefixes
-  findNewPortNames function
-  getCompName function

2025-03-07 23:55 UTC, mastarkey commented
issue is closed and moved to https://github.com/openconfig/featureprofiles/pull/3957

2025-03-07 23:55 UTC, closed without merging