Add DP-2.4 test code
openconfig/featureprofiles pull request #3654
Opened 2024-12-17 18:11 UTC by vishnureddybadveli

Add DP-2.4 test code for police traffic on input interface matching all packets for ARISTA/CISCO.

2024-12-26 22:08 UTC, dplore commented
/fptest virtual

2024-12-27 05:22 UTC, sezhang2 commented
Please resolve the conflict to fix the build error:

_# github.com/openconfig/featureprofiles/internal/deviations
Error: internal/deviations/deviations.go:1270:34: lookupDUTDeviations(dut).GetGribiEncapHeaderUnsupported undefined (type *metadata_go_proto.Metadata_Deviations has no field or method GetGribiEncapHeaderUnsupported)_

2025-01-02 16:19 UTC, vishnureddybadveli commented
> Please resolve the conflict to fix the build error:
> 
> _# github.com/openconfig/featureprofiles/internal/deviations Error: internal/deviations/deviations.go:1270:34: lookupDUTDeviations(dut).GetGribiEncapHeaderUnsupported undefined (type *metadata_go_proto.Metadata_Deviations has no field or method GetGribiEncapHeaderUnsupported)_

Thank you, added missing file metadata.pb.go which resolved the error.

2025-01-05 21:08 UTC, sezhang2 commented
Please fix the failed check

_packets using 1 rate, 2 color marker
F0103 02:18:45.226004    3101 main.go:47] Problems found under feature root.  Please make sure test paths follow feature/<feature>/<subfeature>/<testkind>/<testname>/<testname>_test.go and all tests have an accompanying README.md in the test directory.
exit status 1
Error: Process completed with exit code 1._

2025-01-08 15:29 UTC, vishnureddybadveli commented
> Please fix the failed check
> 
> _packets using 1 rate, 2 color marker F0103 02:18:45.226004 3101 main.go:47] Problems found under feature root. Please make sure test paths follow feature/////_test.go and all tests have an accompanying README.md in the test directory. exit status 1 Error: Process completed with exit code 1._

Thank you, 
Fixed formatting issue with README file.

2025-01-09 08:10 UTC, sezhang2 commented on feature/qos/otg_tests/ingress_police_default/ingress_police_default_test.go
> +	case ondatra.ARISTA:
Do we have a bug/FR to support the OC config instead of CLI config?

2025-01-09 08:15 UTC, sezhang2 approved these changes

2025-01-10 20:31 UTC, dplore requested changes

2025-01-10 20:31 UTC, dplore commented on feature/qos/otg_tests/ingress_police_default/ingress_police_default_test.go
> +	if deviations.GribiEncapHeaderUnsupported(dut) {
This should be a new deviation, specific to qos ingress policing.  As @sezhang2 notes, there should be google internal bugs filed for vendor support of of the QoS OC needed.

2025-01-10 20:31 UTC, dplore commented on feature/qos/otg_tests/ingress_police_default/ingress_police_default_test.go
> +	if deviations.GribiEncapHeaderUnsupported(dut) {
A good name for this new deviation might be   `deviations.QosSchedulerIngressPolicer`

2025-01-10 21:30 UTC, vishnureddybadveli commented on feature/qos/otg_tests/ingress_police_default/ingress_police_default_test.go
> +	if deviations.GribiEncapHeaderUnsupported(dut) {
> This should be a new deviation, specific to qos ingress policing. As @sezhang2 notes, there should be google internal bugs filed for vendor support of of the QoS OC needed.

Yes internal bug exists, I added it to the comments.

2025-01-10 21:31 UTC, vishnureddybadveli commented on feature/qos/otg_tests/ingress_police_default/ingress_police_default_test.go
> +	case ondatra.ARISTA:
Thank you,

Yes internal bug exists, added it to the comments.

2025-01-10 22:12 UTC, vishnureddybadveli commented on feature/qos/otg_tests/ingress_police_default/ingress_police_default_test.go
> +			expectedThroughputPct: 100.0,
Thank you,
As port speed is 1g but traffic is sent at 2g, port should send traffic at full capacity 50% of 2g.

2025-01-13 23:14 UTC, sezhang2 approved these changes

2025-01-22 16:38 UTC, sezhang2 commented
Please resolve conflicts.

2025-01-22 17:26 UTC, dplore approved these changes

2025-01-22 17:45 UTC, dplore approved these changes

2025-01-22 17:52 UTC, sezhang2 approved these changes

2025-01-22 18:17 UTC, merged