Update sub test case to retain TTL=1 for incoming packets with TTL = 1
openconfig/featureprofiles pull request #3656
Opened 2024-12-17 20:28 UTC by vishnureddybadveli

Update sub test case to retain TTL=1 for incoming packets with TTL = 1

2024-12-17 23:15 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +```proto
Please revise the format to use what is in TE-18.1.1 (proto specific format)

ref: https://github.com/openconfig/featureprofiles/pull/3656/files#diff-a6b35105c1accdb1889d9c529f4a13d6844d4a9844a90f3d3f736eba728502c5R48-R78

2024-12-17 23:15 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +              inner_ip_ttl_min: 1
Please add a TODO comment as this field does not exist in the OC AFT model (yet) and is also not yet present in gRIBI proto

2024-12-17 23:15 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +* Validate afts next hop counters
For this subtest, we are only checking the IP TTL, so this next hop counter validation can be removed.

2024-12-17 23:15 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +  * Validate inner packet ttl as 1.
Add a validation for the outer ttl as well (it should also be the value specified in "outer_ip-ttl")

2024-12-19 20:40 UTC, dplore submitted a review, later dismissed

2024-12-19 22:26 UTC, dplore commented
@robshakir for 2nd review+approval since other gribi feature owners are unavailable or not connected to this use case.

2025-02-26 23:08 UTC, dplore requested changes

2025-02-26 23:08 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "ip-ttl": 1
This will force the outer packet ttl to be set to 1 no matter what the inner/payload packet's TTL is.  See:

https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-network-instance.html#network-instances-network-instance-afts-next-hops-next-hop-encap-headers-encap-header-udp-v4-state-ip-ttl

There currently isn't any OC config path or gRIBI proto defined to implement the description of this new subtest TE-18.1.5.  You can propose a new field

2025-02-26 23:08 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +redirect and inner packet TTL = 1.
I think this is intended to be programmed using gRIBI.modify, correct?  The JSON below looks like what would be used in a gnmi.Set.  You'll need some proto encoded structure like in TE-18.1.1.  You should be able to copy TE-18.1.1 and add a new (proposed) field for this special TTL behavior.  Perhaps named something like  `preserve_ttl_1` or `ttl_1_exception`.

2025-02-26 23:08 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "ip-ttl": 1
See comment above regarding adding a TODO for a new gRIBI field like `preserve_ttl_1`

2025-02-27 00:17 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +redirect and inner packet TTL = 1.
hmm... I think this will be gnmi set since traffic policy will be used

2025-02-27 00:28 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "ip-ttl": 1
I agree but we go by traffic policy so do we need to propose a new gRIBI field?

2025-02-27 03:47 UTC, arkaab commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +redirect and inner packet TTL = 1.
this will be via vendor CLI.

2025-02-27 03:51 UTC, arkaab commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                      "next-hop-group": "nhg" #TODO: Need to add to model as nhg will be doing encap and setting TTL.
Is this already a field in NHG ? 
Is the proposal here to have a separate NHG just for cloud router traffic ?

2025-02-27 03:58 UTC, arkaab commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                      "next-hop-group": "nhg" #TODO: Need to add to model as nhg will be doing encap and setting TTL.
Modeling this as an encap parameter is fine.

2025-02-27 18:55 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +redirect and inner packet TTL = 1.
I agree its not going to be gRIBI per se, although immediate usage is vendor CLI.

2025-02-27 19:58 UTC, jaingaurav12 commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "destination-address": "router_ip"
Can we please make this a generic ? any packets w/ ttl 1 ...... why Router IP ?

2025-02-27 19:58 UTC, jaingaurav12 commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +          "policy-forwarding": {
What about inner IPv4 packets

2025-02-27 21:57 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "destination-address": "router_ip"
We agreed upon match with (Router IP + TTL=1) as we thought there could be use case packets(for example trace route, customer packets) having TTL = 1 not destined to Router.

2025-02-27 22:09 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                      "next-hop-group": "nhg" #TODO: Need to add to model as nhg will be doing encap and setting TTL.
Thank you,

There was an effort from partner team to model a nhg as an encap parameter.(https://github.com/openconfig/public/compare/master...danameme:public:temp1-static-gue)

I was planning to piggyback on it by adding the support for setting TTL in nhg.

2025-02-27 22:12 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +          "policy-forwarding": {
Thank you,

This is complicated currently I do not see a way to do this in a single instruction, my proposal is there would be an additional separate config that would have been pre-provisioned for the HW pipeline to look into inner IPv4 packets. I do not have a way to represent this as of now.

2025-02-27 22:14 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +redirect and inner packet TTL = 1.
Thanks Darren

I do not see any reason we will be using gRIBI.modify.

2025-02-28 18:14 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +          "policy-forwarding": {
Thank you,
The proposal says match on (Router IP + outer IP TTL=1) but specifies action as set inner packet TTL=1.

2025-02-28 18:22 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                      "next-hop-group": "nhg" #TODO: Need to add to model as nhg will be doing encap and setting TTL.
It was decided to drop redirect action instead use action as set ttl = 1

2025-03-04 16:28 UTC, vishnureddybadveli commented
Darren and jaingaurav12,

May I request your approval and merge of the changes.

2025-03-04 21:12 UTC, trlongth commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "ip-ttl": 1
There seems to be an existing field `hop-limit` that match the description with what we are looking here.
Can we use that insetad:
https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-network-instance.html#network-instances-network-instance-policy-forwarding-policies-policy-rules-rule-ipv6-config-hop-limit

2025-03-04 21:27 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "ip-ttl": 1
Ah, I see. Got it.  The action of `set-ip-ttl` sounds good.  I don't see a TODO in the README to add that to the OC models though.

2025-03-04 21:30 UTC, dplore commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "ip-ttl": 1
Thanks @trlongth.  

The rule should include the existing [hop-limit](https://openconfig.net/projects/models/schemadocs/yangdoc/openconfig-network-instance.html#network-instances-network-instance-policy-forwarding-policies-policy-rules-rule-ipv6-config-hop-limit) field.

The action should include a proposed `set-ip-ttl` field.

2025-03-04 21:52 UTC, trlongth commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "ip-ttl": 1
So for my understanding, we should:
- Replace the "ip-ttl" in the rule with "hop-limit".
- Propose a new "set-ip-ttl" in the action.

2025-03-04 22:00 UTC, vishnureddybadveli commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +                        "ip-ttl": 1
Thanks Darren

I agree currently I did not add a OC yet. 
I will create a PR and add path.

2025-03-05 17:42 UTC, trlongth approved these changes

2025-03-05 23:15 UTC, dplore approved these changes

2025-03-05 23:54 UTC, nandanarista reviewed
the policy lgtm

2025-03-06 01:00 UTC, xw-g submitted a review, later dismissed

2025-03-06 01:00 UTC, xw-g commented on feature/gribi/otg_tests/mpls_in_udp/README.md
> +### TE-18.1.5 Rewrite the ingress innner packet TTL = 1, if the incoming TTL = 1.
Is this test already implemented in code? If not, let's add a [TODO] here.

2025-03-06 21:04 UTC, dplore approved these changes

2025-03-07 15:44 UTC, merged