OTG Test gNMI-1.10 update
openconfig/featureprofiles pull request #433
Opened 2022-08-17 21:56 UTC by octpetre

Updating with changes to the ATE test in https://github.com/openconfig/featureprofiles/pull/395

2022-08-22 21:16 UTC, octpetre commented
@liulk could you please assign? Thanks

2022-08-23 16:49 UTC, sezhang2 approved these changes

2022-08-24 19:10 UTC, liulk requested changes

2022-08-24 19:10 UTC, liulk commented on feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +	maxPortVal      = "FFFFFEFF" // Maximum Port Value : https://github.com/openconfig/public/blob/2049164a8bca4cc9f11ffb313ef25c0e87303a24/release/models/p4rt/openconfig-p4rt.yang#L63-L81
```suggestion
	// Maximum Port Value: https://github.com/openconfig/public/blob/2049164a8bca4cc9f11ffb313ef25c0e87303a24/release/models/p4rt/openconfig-p4rt.yang#L81
	maxPortVal      = 0xFFFFFEFF
```

2022-08-24 19:10 UTC, liulk commented on feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +
```suggestion
```

2022-08-24 19:10 UTC, liulk commented on feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +		portID: uint32(maxPortValDec) / 2,
```suggestion
		portID: uint32(maxPortVal) / 2,
```

2022-08-24 19:10 UTC, liulk commented on feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +		portID: uint32(maxPortValDec),
```suggestion
		portID: uint32(maxPortVal),
```

2022-08-24 19:36 UTC, octpetre commented on feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +	maxPortVal      = "FFFFFEFF" // Maximum Port Value : https://github.com/openconfig/public/blob/2049164a8bca4cc9f11ffb313ef25c0e87303a24/release/models/p4rt/openconfig-p4rt.yang#L63-L81
Done

2022-08-24 19:38 UTC, octpetre commented on feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +		portID: uint32(maxPortValDec) / 2,
Done

2022-08-24 19:39 UTC, octpetre commented on feature/gnmi/otg_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +
Done

2022-08-24 20:36 UTC, liulk approved these changes

2022-08-24 20:37 UTC, liulk commented
/gcbrun

2022-08-24 20:55 UTC, merged