Add deviation for interface counter
openconfig/featureprofiles pull request #642
Opened 2022-10-13 06:27 UTC by mojiiba

This pull adds a deviation to use gnmi get at the container level for reading interface counters. It also guards the ipv4/enabled with the related deviation.

2022-10-13 20:41 UTC, liulk requested changes

2022-10-13 20:41 UTC, liulk commented on internal/deviations/deviations.go
> +	CounterLeavesNotUpdated = flag.Bool("deviation_counters_leaves_notupdated", false, "Device updates counters when they are queried at the container level.")
```suggestion
	InterfaceCountersFromContainer = flag.Bool("deviation_interface_counters_from_container", false, "Device only supports querying interface counters from the state container, not from individual counter leaves.")
```

2022-10-13 20:41 UTC, liulk commented on feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +		}
Already done in #641 ?

2022-10-14 05:32 UTC, mojiiba commented on feature/gnmi/ate_tests/telemetry_basic_check_test/telemetry_basic_check_test.go
> +		}
no, I missed this one

2022-10-14 05:57 UTC, mojiiba commented on internal/deviations/deviations.go
> +	CounterLeavesNotUpdated = flag.Bool("deviation_counters_leaves_notupdated", false, "Device updates counters when they are queried at the container level.")
thank you, addressed

2022-10-14 14:41 UTC, liulk approved these changes

2022-10-14 14:41 UTC, liulk commented
/gcbrun

2022-10-14 23:00 UTC, merged