gnoi 5.3 commit to experimental
openconfig/featureprofiles pull request #709
Opened 2022-10-27 23:42 UTC by nraghavendran

test case to address https://github.com/openconfig/featureprofiles/issues/99. 
the test case needs to be made to work later.

2022-10-28 00:32 UTC, sezhang2 commented on feature/experimental/gnoi/copying_debug_files_test/copying_debug_files_test.go
> +	t.Logf("Time elapsed after process restart: ", time.Since(start))
Add %v

2022-10-28 18:35 UTC, nraghavendran commented on feature/experimental/gnoi/copying_debug_files_test/copying_debug_files_test.go
> +	t.Logf("Time elapsed after process restart: ", time.Since(start))
resolved the comment

2022-10-28 20:31 UTC, sezhang2 commented
statistics failure:
=============

@@ -79,7 +79,7 @@
 	req := &hpb.GetRequest{
 		Path: &tpb.Path{
 			Elem: []*tpb.PathElem{
-				&tpb.PathElem{
+				{
 					Name: "components/component/state/software-version",
 				},
 			},

2022-10-28 21:22 UTC, nraghavendran commented
changed to reflect other examples like net/model/operations/gnoice/healthz_test.go

2022-10-28 21:30 UTC, nraghavendran commented
> # statistics failure:
> @@ -79,7 +79,7 @@ req := &hpb.GetRequest{ Path: &tpb.Path{ Elem: []*tpb.PathElem{
> 
> * ```
>     		&tpb.PathElem{
>   ```
> 
> * ```
>     		{
>     			Name: "components/component/state/software-version",
>     		},
>     	},
>   ```

I have changed this more, to reflect existing code for example in net/model/operations/gnoice/healthz_test.go

2022-10-28 21:41 UTC, sezhang2 approved these changes
Please commit the code after checks passed.

2022-10-28 21:42 UTC, sezhang2 commented on feature/experimental/gnoi/copying_debug_files_test/copying_debug_files_test.go
> +	req = &hpb.GetRequest{
Error: vet: feature/experimental/gnoi/copying_debug_files_test/copying_debug_files_test.go:79:2: undeclared name: req
Error: Process completed with exit code 2.

2022-10-28 21:43 UTC, sezhang2 requested changes
Error: vet: feature/experimental/gnoi/copying_debug_files_test/copying_debug_files_test.go:79:2: undeclared name: req
Error: Process completed with exit code 2.

2022-10-31 21:29 UTC, sezhang2 approved these changes

2022-10-31 22:16 UTC, merged