TE 3.2: add a flag to enabl/diable adding a drop route
openconfig/featureprofiles pull request #718
Opened 2022-10-29 07:01 UTC by mojiiba

This pull simply adds a flag to enable/disable adding drop route. Also, please note that the semantics of drop route is a vendor dependent and the expected behavior may need to be captured by static route tests.

2022-12-06 17:53 UTC, xw-g requested changes

2022-12-07 02:31 UTC, mojiiba commented on feature/gribi/ate_tests/weighted_balancing_test/setup_test.go
> +		static.GetOrCreateNextHop("AUTO_drop_2").
sure

2022-12-07 02:37 UTC, mojiiba commented on feature/gribi/ate_tests/weighted_balancing_test/setup_test.go
> +	addNullRoute = flag.Bool("add_drop_route", true, "add a drop route so that when the nexthop interface goes down, the device does not attempt to route packets through the default gateway 0.0.0.0/0.")
the way the discard route is added in this test is not vendor neutral and this does not work as discard route in our devices.  @aaronmillisor can give you more details on this.

2022-12-07 22:21 UTC, xw-g commented on feature/gribi/ate_tests/weighted_balancing_test/setup_test.go
> +	addNullRoute = flag.Bool("add_drop_route", true, "add a drop route so that when the nexthop interface goes down, the device does not attempt to route packets through the default gateway 0.0.0.0/0.")
Yes, deviation flag MUST be a global variable in the deviation.go

2022-12-09 04:15 UTC, mojiiba commented on feature/gribi/ate_tests/weighted_balancing_test/setup_test.go
> +	addNullRoute = flag.Bool("add_drop_route", true, "add a drop route so that when the nexthop interface goes down, the device does not attempt to route packets through the default gateway 0.0.0.0/0.")
thanks, addressed your comment

2022-12-09 04:16 UTC, mojiiba commented on feature/gribi/ate_tests/weighted_balancing_test/setup_test.go
> +		static.GetOrCreateNextHop("AUTO_drop_2").
done

2022-12-19 05:16 UTC, mojiiba commented on feature/gribi/ate_tests/weighted_balancing_test/setup_test.go
> +		static.GetOrCreateNextHop("AUTO_drop_2").
@xw-g please let me if you agree with the changes?

2023-01-05 20:13 UTC, xw-g commented
@vosipchu is investigating some possible augmentation in the infra that we might not need this deviation.

2023-01-18 20:31 UTC, mojiiba commented
closing this pr since the default route will be removed.

2023-01-18 20:31 UTC, closed without merging