Migrate bgp addpath and gracefulrestart to new lib
openconfig/featureprofiles pull request #766
Opened 2022-11-11 20:03 UTC by DanG100

2022-11-11 21:24 UTC, dan-lepage commented
/gcbrun

2022-11-11 22:01 UTC, dan-lepage requested changes
LGTM, except for a few small comment fixes. Is it possible to have ygot generate interface types for the gostructs?  It would be nice if instead of having both `ConfigInterface` and `ConfigOCInterface` we could just have one function that handles both.

2022-11-11 22:24 UTC, DanG100 commented on feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
> +				_, ok := gnmi.Watch(t, otg, nbrPath.SessionState().State(), time.Minute, func(val *ygnmi.Value[otgtelemetry.E_BgpPeer_SessionState]) bool {
the otg yang is defining it's own enum, so the enums aren't (and shouldn't be) the same https://github.com/open-traffic-generator/models-yang/blob/main/models/bgp/open-traffic-generator-bgp.yang#L90 

if it imported to oc enum, then reusing the same type might be possible, (but probably difficult to implement and have caveats like what if a module augments the imported enum with a new type how would that work)

2022-11-11 22:25 UTC, dan-lepage commented
/gcbrun

2022-11-11 22:27 UTC, dan-lepage commented on feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
> +				_, ok := gnmi.Watch(t, otg, nbrPath.SessionState().State(), time.Minute, func(val *ygnmi.Value[otgtelemetry.E_BgpPeer_SessionState]) bool {
Yeah, I guess the real fix would involve standardizing a bunch of these enums and splitting them into a separate package, which would be a lot of work for very little actual payoff.

2022-11-11 22:27 UTC, dan-lepage approved these changes

2022-11-11 22:31 UTC, DanG100 commented on internal/attrs/attrs.go
> +// ConfigInterface configures an OpenConfig interface with these attributes.
fixed comments. 
re generating a go interfaces, that'd be a lot of generated code for little benefit. Also for it to work all the methods would have to return interface types (the GetOrCreate...)

2022-11-14 18:04 UTC, dan-lepage commented on internal/attrs/attrs.go
> +// ConfigInterface configures an OpenConfig interface with these attributes.
Oh, right. That's too bad - it means any helper that uses OC must be tied to a specific built library - but I don't think we can do anything about that.

2022-11-14 18:04 UTC, merged