RT-1.3: BGP Route Propagation (KNE/OTG) - Adding delay of 5 seconds
openconfig/featureprofiles pull request #832
Opened 2022-12-02 18:11 UTC by stthummuri

to come up on virtual environment

2022-12-02 18:13 UTC, stthummuri commented
Added a delay of 5 seconds since it would take that time for bgp neighbors to come up on virtual environment

2022-12-19 17:24 UTC, greg-dennis requested changes

2022-12-19 17:24 UTC, greg-dennis commented on feature/bgp/addpath/otg_tests/route_propagation_test/route_propagation_test.go
> +		time.Sleep(5 * time.Second)
I would add 5 seconds to the Await() call instead

2023-01-04 04:21 UTC, greg-dennis commented
@stthummuri, are you going to continue this PR and resolve the rebase check?

2023-01-04 05:24 UTC, stthummuri commented
> Details

@greg-dennis, yes I will use this PR only and will resolve the rebase check tomorrow

2023-01-04 20:16 UTC, stthummuri commented
> @stthummuri, are you going to continue this PR and resolve the rebase check?

Resolved the rebase check. Can you please review and merge

2023-01-04 21:21 UTC, greg-dennis approved these changes
Re-approve

2023-01-04 21:22 UTC, merged