making "Dual RP/SUP" to be required for the test to pass
openconfig/featureprofiles pull request #914
Opened 2022-12-15 22:25 UTC by averasko

PiperOrigin-RevId: 494593179

making "Dual RP/SUP" to be required for the test to pass (Arista 7208 and Nokia will start failing it)

2022-12-15 22:57 UTC, sezhang2 commented
/gcbrun

2022-12-16 03:14 UTC, sezhang2 submitted a review, later dismissed

2022-12-19 19:20 UTC, liulk approved these changes

2022-12-19 19:21 UTC, liulk commented
/gcbrun

2022-12-19 19:25 UTC, liulk requested changes

2022-12-19 19:25 UTC, liulk commented on internal/fptest/doc.go
> +	_ "google3/third_party/openconfig/featureprofiles/internal/args/args"             // keep
Please fix the import paths.

2022-12-19 19:26 UTC, liulk commented on internal/fptest/doc.go
> +	_ "google3/third_party/openconfig/featureprofiles/internal/deviations/deviations" // keep
```suggestion
	_ "github.com/openconfig/featureprofiles/internal/args/args"             // keep
	_ "github.com/openconfig/featureprofiles/internal/deviations/deviations" // keep
```

2022-12-19 21:42 UTC, sezhang2 approved these changes

2022-12-19 21:42 UTC, sezhang2 commented
/gcbrun

2022-12-19 22:06 UTC, liulk commented on internal/fptest/doc.go
> +	_ "github.com/openconfig/featureprofiles/internal/deviations/deviations" // keep
```suggestion
	_ "github.com/openconfig/featureprofiles/internal/args"             // keep
	_ "github.com/openconfig/featureprofiles/internal/deviations" // keep
```

2022-12-19 23:34 UTC, sezhang2 approved these changes

2022-12-19 23:34 UTC, sezhang2 commented
/gcbrun

2022-12-20 00:09 UTC, sezhang2 commented
/gcbrun

2022-12-20 02:04 UTC, sezhang2 approved these changes

2022-12-20 15:21 UTC, liulk approved these changes

2022-12-20 15:21 UTC, merged