Code commit for DP-1.4
openconfig/featureprofiles pull request #969
Opened 2023-01-11 08:45 UTC by azubaidhar

Added functions to configure OC-QOS forwarding-classes,  queues, classifiers, attach classifier to interface so expected number of queues/packets are seen.

Thanks,
Abdul Zubaidhar .A

2023-01-11 09:21 UTC, sezhang2 commented
/gcbrun

2023-02-06 19:45 UTC, greg-dennis approved these changes
Approving for Go only

2023-02-06 19:45 UTC, greg-dennis commented on feature/experimental/qos/ate_tests/qos_output_queue_counters_test/qos_output_queue_counters_test.go
> +	t.Logf("qos forwarding groups config cases: %v", cases)
Log lines should be capitalized

2023-02-06 21:24 UTC, sezhang2 commented
I updated the test and added the config. Can you pick the latest code?

2023-02-06 21:26 UTC, sezhang2 requested changes
Please pick the latest code.

2023-02-07 18:59 UTC, greg-dennis commented
/gcbrun

2023-02-09 01:46 UTC, sgirishj commented
PR is outdated due to https://github.com/openconfig/featureprofiles/pull/1018

Hence closing.

2023-02-09 01:46 UTC, closed without merging